"""
Tests for the real hardware IO, run against the vendors' simulators.

Generated by Claude. REV, CTRE and Studica each ship a simulated version of
their device, so these tests check the parts we can get wrong without a
robot: units (meters and radians, not rotations and RPM), the offset and
wrap-around, signs, and that every controller accepts its settings. Whether
the wheels really point the right way is checked on blocks with the module
check in test mode.

The single module uses CAN IDs 15 to 17, which are reserved for tests.
Phoenix 6 and NavX have no RobotPy 2027 builds yet, so those tests are
skipped there.
"""

import dataclasses
import math
import time

import pytest
import rev

from commands.drive.module_check import HOLD_S, STEPS_DEG, ModuleCheck
from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain.drivetrain_sim import DrivetrainSim
from subsystem.drivetrain.io.abs_encoder_io import AbsoluteEncoderInputs
from subsystem.drivetrain.io.gyro_io import GyroInputs
from subsystem.drivetrain.io.gyro_io_onboard import YawUnwrapper
from subsystem.drivetrain.io.module_io import ModuleInputs
from subsystem.drivetrain.io.module_io_spark import ModuleIOSpark, drive_config, steer_config

try:
    from wpimath.system.plant import DCMotor
except ImportError:  # RobotPy 2027
    from wpimath import DCMotor  # pyright: ignore[reportAttributeAccessIssue]

TEST_CORNER = dataclasses.replace(CONFIG.corners[0], drive_can_id=15, steer_can_id=16, encoder_can_id=17)


@pytest.fixture(scope="module")
def spark_module():
    """One SPARK MAX module and its REV simulators, shared by the tests below."""
    io = ModuleIOSpark(CONFIG, TEST_CORNER)
    return io, rev.SparkMaxSim(io.drive, DCMotor.NEO(1)), rev.SparkMaxSim(io.steer, DCMotor.NEO(1))


class TestSparkModule:
    def test_both_controllers_accept_their_settings(self, spark_module):
        io, _, _ = spark_module
        assert io.configured

    def test_drive_counts_in_meters(self, spark_module):
        io, drive_sim, _ = spark_module
        before = ModuleInputs()
        io.update_inputs(before)
        for _ in range(50):  # 1 m/s for 1 s
            drive_sim.iterate(1.0, 12.0, 0.02)
        after = ModuleInputs()
        io.update_inputs(after)
        assert after.drive_position_m - before.drive_position_m == pytest.approx(1.0, rel=1e-3)
        assert after.drive_connected

    def test_steer_angle_is_set_and_wrapped(self, spark_module):
        io, _, _ = spark_module
        inputs = ModuleInputs()
        io.reset_steer_angle(1.0)
        io.update_inputs(inputs)
        assert inputs.steer_angle_rad == pytest.approx(1.0, abs=1e-6)
        io.reset_steer_angle(4.0)  # past pi: reads as 4 - 2 pi
        io.update_inputs(inputs)
        assert inputs.steer_angle_rad == pytest.approx(4.0 - math.tau, abs=1e-6)

    def test_setpoints_are_in_our_units(self, spark_module):
        io, drive_sim, steer_sim = spark_module
        io.set_drive_velocity(2.5, feedforward_volts=3.0)
        io.set_steer_angle(-0.7)
        assert drive_sim.getSetpoint() == pytest.approx(2.5)
        assert steer_sim.getSetpoint() == pytest.approx(-0.7)


class TestSparkSettings:
    """Check the settings themselves, before they are sent to a controller."""

    def flat(self, cfg):
        return cfg.flatten()

    def test_drive_and_steer_settings_differ(self):
        drive = drive_config(CONFIG, CONFIG.corners[0])
        steer = steer_config(CONFIG)
        assert self.flat(drive) != self.flat(steer)

    def test_drive_inversion_follows_the_corner(self):
        normal = dataclasses.replace(CONFIG.corners[0], drive_inverted=False)
        flipped = dataclasses.replace(CONFIG.corners[0], drive_inverted=True)
        assert self.flat(drive_config(CONFIG, normal)) != self.flat(drive_config(CONFIG, flipped))


@pytest.fixture(scope="module")
def cancoder():
    pytest.importorskip("phoenix6")
    from subsystem.drivetrain.io.abs_encoder_cancoder import AbsoluteEncoderIOCANcoder

    return AbsoluteEncoderIOCANcoder(CONFIG, TEST_CORNER)


def read_when_ready(encoder, expected_raw, tries=100):
    """Phoenix's simulator delivers new values a few milliseconds later, so wait for this one."""
    inputs = AbsoluteEncoderInputs()
    for _ in range(tries):
        encoder.update_inputs(inputs)
        if inputs.connected and abs(inputs.raw_rot - expected_raw) < 2e-3:
            return inputs
        time.sleep(0.01)
    return inputs


class TestCANcoder:
    def test_accepts_its_settings(self, cancoder):
        assert cancoder.configured

    @pytest.mark.parametrize("raw", [0.1, -0.3, 0.45])
    def test_offset_is_added_and_wrapped(self, cancoder, raw):
        cancoder.encoder.sim_state.set_raw_position(raw)
        inputs = read_when_ready(cancoder, raw)
        assert inputs.connected
        assert inputs.raw_rot == pytest.approx(raw, abs=2e-3)
        expected = math.remainder((raw + TEST_CORNER.encoder_offset_rot) * math.tau, math.tau)
        assert math.remainder(inputs.angle_rad - expected, math.tau) == pytest.approx(0.0, abs=0.01)
        assert -math.pi <= inputs.angle_rad < math.pi


@pytest.fixture(scope="module")
def navx_gyro():
    pytest.importorskip("navx")
    from wpilib.simulation import SimDeviceSim

    from subsystem.drivetrain.io.gyro_io_navx import GyroIONavX

    gyro = GyroIONavX(CONFIG)
    return gyro, SimDeviceSim("navX-Sensor[4]")


class TestNavX:
    def test_clockwise_navx_reads_counterclockwise_positive(self, navx_gyro):
        gyro, device = navx_gyro
        device.getBoolean("Connected").set(True)
        device.getDouble("Yaw").set(-90.0)  # NavX: 90 degrees counterclockwise
        inputs = GyroInputs()
        for _ in range(50):
            gyro.update_inputs(inputs)
            if inputs.connected and abs(inputs.yaw_rad) > 0.1:
                break
            time.sleep(0.01)
        assert inputs.connected
        assert inputs.yaw_rad == pytest.approx(math.pi / 2)


class TestYawUnwrapper:
    def test_two_full_turns_keep_counting(self):
        unwrap = YawUnwrapper()
        total = 0.0
        for step in range(1, 73):  # 72 steps of 10 degrees = two turns
            total = unwrap.update(math.remainder(math.radians(10 * step), math.tau))
        assert total == pytest.approx(4 * math.pi)

    def test_turning_back_counts_down(self):
        unwrap = YawUnwrapper()
        unwrap.update(math.radians(175))
        unwrap.update(math.radians(-175))  # 10 degrees further counterclockwise
        assert math.degrees(unwrap.update(math.radians(175))) == pytest.approx(175)


class TestModuleCheck:
    def test_cycles_through_each_direction(self):
        check = ModuleCheck(DrivetrainSim(CONFIG).drivetrain)
        seen = [check.target_degrees(HOLD_S * i + 0.1) for i in range(len(STEPS_DEG) + 1)]
        assert seen == [*STEPS_DEG, STEPS_DEG[0]]

    def test_wheels_point_exactly_where_asked(self):
        # From 180 back to 0 the short way would leave the wheels at 180
        # rolling backward; the check must really turn them round.
        sim = DrivetrainSim(CONFIG)
        drive = sim.drivetrain
        for degrees in (180.0, 0.0):
            for _ in range(40):
                drive.periodic()
                for module in drive.modules:
                    module.set_angle(math.radians(degrees), short_way=False)
            for io in sim.module_sims:
                error = math.remainder(io.true_steer_angle_rad - math.radians(degrees), math.tau)
                assert abs(error) < math.radians(1)


def test_build_drivetrain_makes_every_device():
    pytest.importorskip("phoenix6")
    from subsystem.drivetrain.drivetrain_hardware import build_drivetrain

    from subsystem.drivetrain.io.gyro_io_sim import GyroIOSim

    # A second NavX in one test process upsets the NavX simulator, so the gyro
    # is simulated here; the NavX has its own test above.
    drive = build_drivetrain(CONFIG, gyro=GyroIOSim())
    assert len(drive.modules) == 4
    assert all(module.io.configured for module in drive.modules)  # pyright: ignore[reportAttributeAccessIssue]
