"""
Tests for the swerve math in ``subsystem/drivetrain/swerve_math.py``.

Generated by Claude. Each function is checked on its own, and where WPILib
has the same function the answers are compared with WPILib's (on RobotPy
2026; the 2027 run skips those because the classes were renamed).
"""

import math

import pytest

from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain.swerve_math import (
    ChassisSpeeds,
    ModuleTarget,
    Pose,
    cosine_scale,
    desaturate,
    discretize,
    field_to_robot,
    forward_kinematics,
    inverse_kinematics,
    optimize,
    pose_exp,
)

CORNERS = [(c.x_m, c.y_m) for c in CONFIG.corners]
# A long, narrow robot, so nothing relies on the modules being in a square.
RECTANGLE = [(0.35, 0.22), (0.35, -0.22), (-0.35, 0.22), (-0.35, -0.22)]

MIXED_SPEEDS = [
    ChassisSpeeds(1, 0, 0),
    ChassisSpeeds(0, -2, 0),
    ChassisSpeeds(0, 0, 3),
    ChassisSpeeds(1.2, -0.4, 1.7),
    ChassisSpeeds(-3.0, 1.0, -4.0),
]


def angle_error(a, b):
    """Smallest difference between two angles, radians."""
    return abs(math.remainder(a - b, math.tau))


def wpilib_2026():
    """WPILib's geometry and kinematics modules, or skip the test on 2027."""
    try:
        from wpimath import geometry, kinematics
    except ImportError:
        pytest.skip("2027 renamed these classes; the 2026 run covers this")
    return geometry, kinematics


def assert_speeds_equal(a, b, abs_tol=1e-9):
    assert a.vx_mps == pytest.approx(b.vx_mps, abs=abs_tol)
    assert a.vy_mps == pytest.approx(b.vy_mps, abs=abs_tol)
    assert a.omega_rad_per_s == pytest.approx(b.omega_rad_per_s, abs=abs_tol)


class TestFieldToRobot:
    def test_heading_zero_changes_nothing(self):
        assert_speeds_equal(field_to_robot(ChassisSpeeds(1, 2, 3), 0.0), ChassisSpeeds(1, 2, 3))

    def test_facing_backward_flips_translation(self):
        s = field_to_robot(ChassisSpeeds(1, 2, 3), math.pi)
        assert_speeds_equal(s, ChassisSpeeds(-1, -2, 3))

    def test_round_trip(self):
        s = field_to_robot(field_to_robot(ChassisSpeeds(1, 2, 3), 0.7), -0.7)
        assert_speeds_equal(s, ChassisSpeeds(1, 2, 3))

    def test_matches_wpilib(self):
        geometry, kinematics = wpilib_2026()
        ours = field_to_robot(ChassisSpeeds(1.5, -0.5, 2.5), 2.1)
        theirs = kinematics.ChassisSpeeds.fromFieldRelativeSpeeds(1.5, -0.5, 2.5, geometry.Rotation2d(2.1))
        assert_speeds_equal(ours, ChassisSpeeds(theirs.vx, theirs.vy, theirs.omega))


class TestDiscretize:
    def test_matches_wpilib(self):
        _, kinematics = wpilib_2026()
        ours = discretize(ChassisSpeeds(1.5, -0.5, 2.5), 0.02)
        theirs = kinematics.ChassisSpeeds.discretize(1.5, -0.5, 2.5, 0.02)
        assert_speeds_equal(ours, ChassisSpeeds(theirs.vx, theirs.vy, theirs.omega))

    @pytest.mark.parametrize("speeds", MIXED_SPEEDS)
    def test_one_loop_lands_where_the_straight_line_goes(self, speeds):
        # The whole point of discretize: holding the corrected speeds for one
        # loop, following the real arc, ends exactly at (vx*dt, vy*dt).
        dt = 0.02
        end = pose_exp(Pose(), discretize(speeds, dt), dt)
        assert end.x_m == pytest.approx(speeds.vx_mps * dt, abs=1e-12)
        assert end.y_m == pytest.approx(speeds.vy_mps * dt, abs=1e-12)
        assert end.heading_rad == pytest.approx(speeds.omega_rad_per_s * dt)

    def test_tiny_spin_uses_the_small_angle_path(self):
        out = discretize(ChassisSpeeds(1.0, 0.0, 1e-8), 0.02)
        assert out.vx_mps == pytest.approx(1.0)
        assert abs(out.vy_mps) < 1e-9


class TestInverseKinematics:
    @pytest.mark.parametrize("speeds", MIXED_SPEEDS)
    def test_matches_wpilib(self, speeds):
        geometry, kinematics = wpilib_2026()
        wpi = kinematics.SwerveDrive4Kinematics(*[geometry.Translation2d(x, y) for x, y in RECTANGLE])
        theirs = wpi.toSwerveModuleStates(
            kinematics.ChassisSpeeds(speeds.vx_mps, speeds.vy_mps, speeds.omega_rad_per_s)
        )
        for ours, wheel in zip(inverse_kinematics(speeds, RECTANGLE), theirs):
            assert ours.speed_mps == pytest.approx(wheel.speed)
            assert angle_error(ours.angle_rad, wheel.angle.radians()) < 1e-9

    def test_spin_in_place_wheel_speed_is_omega_times_radius(self):
        for t in inverse_kinematics(ChassisSpeeds(0, 0, 2.0), CORNERS):
            assert t.speed_mps == pytest.approx(2.0 * CONFIG.drive_base_radius_m)

    def test_standing_still_gives_zero_speed_and_angle(self):
        assert inverse_kinematics(ChassisSpeeds(), CORNERS) == [ModuleTarget(0.0, 0.0)] * 4

    def test_strafe_left_points_every_wheel_left(self):
        for t in inverse_kinematics(ChassisSpeeds(0, 1.0, 0), RECTANGLE):
            assert t.speed_mps == pytest.approx(1.0)
            assert t.angle_rad == pytest.approx(math.pi / 2)


class TestForwardKinematics:
    @pytest.mark.parametrize("corners", [CORNERS, RECTANGLE])
    @pytest.mark.parametrize("speeds", MIXED_SPEEDS)
    def test_round_trip(self, speeds, corners):
        back = forward_kinematics(inverse_kinematics(speeds, corners), corners)
        assert_speeds_equal(back, speeds)

    def test_matches_wpilib_when_a_wheel_slips(self):
        # One wheel reads 30% fast, so no robot motion fits all four exactly;
        # both versions should pick the same best fit.
        geometry, kinematics = wpilib_2026()
        wheels = inverse_kinematics(ChassisSpeeds(1.0, 0.3, 0.8), RECTANGLE)
        wheels[0] = ModuleTarget(wheels[0].speed_mps * 1.3, wheels[0].angle_rad)
        wpi = kinematics.SwerveDrive4Kinematics(*[geometry.Translation2d(x, y) for x, y in RECTANGLE])
        states = [kinematics.SwerveModuleState(w.speed_mps, geometry.Rotation2d(w.angle_rad)) for w in wheels]
        theirs = wpi.toChassisSpeeds(tuple(states))
        assert_speeds_equal(forward_kinematics(wheels, RECTANGLE), ChassisSpeeds(theirs.vx, theirs.vy, theirs.omega))

    def test_one_slipping_wheel_is_averaged_out(self):
        # Driving straight with one wheel reading 4% fast: the answer is the
        # average of the four wheels, not the slipping wheel's speed.
        wheels = [ModuleTarget(1.0, 0.0)] * 3 + [ModuleTarget(1.04, 0.0)]
        s = forward_kinematics(wheels, CORNERS)
        assert s.vx_mps == pytest.approx(1.01)
        assert abs(s.vy_mps) < 1e-9


class TestDesaturate:
    def test_keeps_direction(self):
        targets = inverse_kinematics(ChassisSpeeds(4.0, 0.0, 6.0), CORNERS)
        out = desaturate(targets, 4.0)
        assert max(t.speed_mps for t in out) == pytest.approx(4.0)
        ratios = {round(o.speed_mps / t.speed_mps, 9) for o, t in zip(out, targets)}
        assert len(ratios) == 1

    def test_under_the_limit_changes_nothing(self):
        targets = [ModuleTarget(1.0, 0.1), ModuleTarget(-2.0, 0.2)]
        assert desaturate(targets, 4.5) == targets

    def test_backward_wheel_counts_toward_the_limit(self):
        out = desaturate([ModuleTarget(-6.0, 0.0), ModuleTarget(3.0, 1.0)], 3.0)
        assert [t.speed_mps for t in out] == pytest.approx([-3.0, 1.5])
        assert [t.angle_rad for t in out] == [0.0, 1.0]

    def test_no_wheels(self):
        assert desaturate([], 4.0) == []


class TestOptimize:
    @pytest.mark.parametrize("target_deg, current_deg", [(170, 0), (-100, 0), (0, 179), (45, -135), (720, 10)])
    def test_never_turns_more_than_90(self, target_deg, current_deg):
        target = ModuleTarget(1.0, math.radians(target_deg))
        out = optimize(target, math.radians(current_deg))
        assert angle_error(out.angle_rad, math.radians(current_deg)) <= math.pi / 2 + 1e-9
        # Same wheel motion either way: the speed arrow is unchanged.
        assert out.speed_mps * math.cos(out.angle_rad) == pytest.approx(math.cos(target.angle_rad))
        assert out.speed_mps * math.sin(out.angle_rad) == pytest.approx(math.sin(target.angle_rad))

    def test_small_turn_is_left_alone(self):
        target = ModuleTarget(2.0, math.radians(30))
        assert optimize(target, 0.0) == target


class TestCosineScale:
    @pytest.mark.parametrize("error_deg, factor", [(0, 1.0), (60, 0.5), (90, 0.0), (-60, 0.5)])
    def test_scales_by_cosine_of_the_angle_error(self, error_deg, factor):
        out = cosine_scale(ModuleTarget(2.0, 0.0), math.radians(error_deg))
        assert out.speed_mps == pytest.approx(2.0 * factor, abs=1e-12)
        assert out.angle_rad == 0.0


class TestPoseExp:
    def test_no_motion(self):
        assert pose_exp(Pose(1.0, 2.0, 0.5), ChassisSpeeds(), 0.02) == Pose(1.0, 2.0, 0.5)

    def test_spin_in_place_only_turns(self):
        p = pose_exp(Pose(1.0, 2.0, 0.0), ChassisSpeeds(0, 0, 2.0), 0.5)
        assert (p.x_m, p.y_m, p.heading_rad) == pytest.approx((1.0, 2.0, 1.0))

    def test_full_circle_comes_back_to_the_start(self):
        # Driving forward while turning at a constant rate traces a circle.
        p = pose_exp(Pose(), ChassisSpeeds(1.0, 0.0, 1.0), math.tau)
        assert p.x_m == pytest.approx(0.0, abs=1e-9)
        assert p.y_m == pytest.approx(0.0, abs=1e-9)

    @pytest.mark.parametrize("speeds", MIXED_SPEEDS)
    def test_matches_wpilib(self, speeds):
        geometry, _ = wpilib_2026()
        start = Pose(1.0, 2.0, 0.5)
        dt = 0.3
        ours = pose_exp(start, speeds, dt)
        twist = geometry.Twist2d(speeds.vx_mps * dt, speeds.vy_mps * dt, speeds.omega_rad_per_s * dt)
        theirs = geometry.Pose2d(1.0, 2.0, geometry.Rotation2d(0.5)).exp(twist)
        assert ours.x_m == pytest.approx(theirs.X())
        assert ours.y_m == pytest.approx(theirs.Y())
        assert angle_error(ours.heading_rad, theirs.rotation().radians()) < 1e-9
