"""
Tests for one swerve module (``subsystem/drivetrain/module.py``) on its own.

Generated by Claude. Most tests use small fake IO classes that record what
the module asks the motors to do, so each check is about the module's own
logic: seeding, the dead-encoder flag, re-seeding, and how a target becomes
motor commands. One test uses the full module sim to check seeding against
the simulated wheel. The drivetrain tests cover all four modules together.
"""

import math

import pytest

from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain.io.abs_encoder_io import AbsoluteEncoderInputs, AbsoluteEncoderIO
from subsystem.drivetrain.io.abs_encoder_sim import AbsoluteEncoderIOSim
from subsystem.drivetrain.io.module_io import ModuleInputs, ModuleIO
from subsystem.drivetrain.io.module_io_sim import ModuleIOSim, ModuleSimOptions
from subsystem.drivetrain.module import RESEED_TOLERANCE_RAD, SEED_TIMEOUT_LOOPS, STILL_RAD_PER_S, SwerveModule
from subsystem.drivetrain.swerve_math import ModuleTarget

CORNER = CONFIG.corners[0]


class FakeModuleIO(ModuleIO):
    """Motors that report what the test sets and remember the last command."""

    def __init__(self) -> None:
        self.steer_angle_rad = 0.0
        self.steer_velocity_rad_per_s = 0.0
        self.connected = True
        self.drive_velocity = None
        self.drive_ff_volts = None
        self.drive_volts = None
        self.steer_target = None
        self.steer_volts = None
        self.resets: list[float] = []

    def update_inputs(self, inputs: ModuleInputs) -> None:
        inputs.drive_connected = self.connected
        inputs.steer_connected = self.connected
        inputs.steer_angle_rad = self.steer_angle_rad
        inputs.steer_velocity_rad_per_s = self.steer_velocity_rad_per_s

    def set_drive_velocity(self, velocity_mps: float, feedforward_volts: float = 0.0) -> None:
        self.drive_velocity, self.drive_ff_volts, self.drive_volts = velocity_mps, feedforward_volts, None

    def set_drive_voltage(self, volts: float) -> None:
        self.drive_volts, self.drive_velocity = volts, None

    def set_steer_angle(self, angle_rad: float) -> None:
        self.steer_target, self.steer_volts = angle_rad, None

    def set_steer_voltage(self, volts: float) -> None:
        self.steer_volts, self.steer_target = volts, None

    def reset_steer_angle(self, angle_rad: float) -> None:
        self.steer_angle_rad = angle_rad
        self.resets.append(angle_rad)


class FakeEncoder(AbsoluteEncoderIO):
    """An absolute encoder that reports whatever angle the test sets."""

    def __init__(self, angle_rad: float = 0.0, connected: bool = True) -> None:
        self.angle_rad = angle_rad
        self.connected = connected

    def update_inputs(self, inputs: AbsoluteEncoderInputs) -> None:
        inputs.connected = self.connected
        inputs.angle_rad = self.angle_rad if self.connected else 0.0


def make_module(encoder_angle_rad=0.0, encoder_connected=True):
    io = FakeModuleIO()
    encoder = FakeEncoder(encoder_angle_rad, encoder_connected)
    return SwerveModule(CORNER, CONFIG, io, encoder), io, encoder


def seeded_module(angle_rad=0.0):
    module, io, encoder = make_module(angle_rad)
    module.periodic(disabled=True)
    return module, io, encoder


class TestSeeding:
    def test_first_good_reading_seeds_the_steer_encoder(self):
        module, io, _ = make_module(encoder_angle_rad=1.2)
        assert not module.seeded
        module.periodic(disabled=True)
        assert module.seeded
        assert io.resets == [1.2]
        # The angle is right on the same loop, not one loop later.
        assert module.angle_rad == 1.2

    def test_seeds_against_the_simulated_wheel(self):
        io = ModuleIOSim(CONFIG, ModuleSimOptions(initial_steer_angle_rad=-2.0))
        module = SwerveModule(CORNER, CONFIG, io, AbsoluteEncoderIOSim.for_module(io, CORNER))
        module.periodic(disabled=True)
        module.periodic(disabled=True)
        assert module.angle_rad == pytest.approx(-2.0, abs=1e-6)

    def test_dead_encoder_is_flagged_after_the_timeout(self):
        module, _, _ = make_module(encoder_connected=False)
        for _ in range(SEED_TIMEOUT_LOOPS - 1):
            module.periodic(disabled=True)
        assert not module.encoder_failed
        module.periodic(disabled=True)
        assert module.encoder_failed
        assert not module.seeded
        assert not module.healthy

    def test_encoder_that_answers_late_clears_the_flag(self):
        module, _, encoder = make_module(encoder_angle_rad=0.5, encoder_connected=False)
        for _ in range(SEED_TIMEOUT_LOOPS):
            module.periodic(disabled=True)
        assert module.encoder_failed
        encoder.connected = True
        module.periodic(disabled=True)
        assert module.seeded
        assert not module.encoder_failed


class TestReseed:
    def test_reseeds_while_disabled_when_the_angles_disagree(self):
        module, io, encoder = seeded_module(0.0)
        encoder.angle_rad = math.radians(5)
        module.periodic(disabled=True)
        assert module.reseed_count == 1
        assert io.resets[-1] == encoder.angle_rad

    def test_small_disagreement_is_left_alone(self):
        module, _, encoder = seeded_module(0.0)
        encoder.angle_rad = RESEED_TOLERANCE_RAD / 2
        module.periodic(disabled=True)
        assert module.reseed_count == 0
        assert module.angle_disagreement_rad == pytest.approx(RESEED_TOLERANCE_RAD / 2)

    def test_never_reseeds_while_enabled(self):
        module, _, encoder = seeded_module(0.0)
        encoder.angle_rad = math.radians(5)
        module.periodic(disabled=False)
        assert module.reseed_count == 0

    def test_never_reseeds_while_the_wheel_is_turning(self):
        module, io, encoder = seeded_module(0.0)
        encoder.angle_rad = math.radians(5)
        io.steer_velocity_rad_per_s = STILL_RAD_PER_S * 2
        module.periodic(disabled=True)
        assert module.reseed_count == 0

    def test_disagreement_wraps_around_180_degrees(self):
        # 179 and -179 degrees are only 2 degrees apart, not 358.
        module, io, encoder = seeded_module(math.radians(179))
        encoder.angle_rad = math.radians(-179.5)
        module.periodic(disabled=True)
        assert module.angle_disagreement_rad == pytest.approx(math.radians(1.5))
        assert module.reseed_count == 0


class TestSetTarget:
    def test_unseeded_module_stays_stopped(self):
        module, io, _ = make_module(encoder_connected=False)
        module.periodic(disabled=False)
        module.set_target(ModuleTarget(2.0, 1.0))
        assert io.drive_volts == 0.0
        assert io.steer_volts == 0.0
        assert module.setpoint == ModuleTarget()

    def test_sends_angle_speed_and_feedforward(self):
        module, io, _ = seeded_module(0.0)
        module.set_target(ModuleTarget(2.0, 0.0))
        assert io.steer_target == 0.0
        assert io.drive_velocity == 2.0
        assert io.drive_ff_volts == pytest.approx(CONFIG.drive_feedforward_volts(2.0))

    def test_turns_the_short_way_and_rolls_backward(self):
        module, io, _ = seeded_module(0.0)
        module.set_target(ModuleTarget(1.0, math.radians(170)))
        assert io.steer_target == pytest.approx(math.radians(-10))
        assert io.drive_velocity < 0

    def test_slows_while_still_turning(self):
        module, io, _ = seeded_module(0.0)
        module.set_target(ModuleTarget(2.0, math.radians(60)))
        assert io.drive_velocity == pytest.approx(1.0)
        assert io.drive_ff_volts == pytest.approx(CONFIG.drive_feedforward_volts(1.0))

    def test_stopped_target_keeps_the_last_angle(self):
        module, io, _ = seeded_module(0.0)
        module.set_target(ModuleTarget(1.0, 0.8))
        module.set_target(ModuleTarget(0.0, 0.0))
        assert io.steer_target == pytest.approx(0.8)
        assert io.drive_velocity == 0.0

    def test_stop_keeps_the_angle_for_next_time(self):
        module, io, _ = seeded_module(0.0)
        module.set_target(ModuleTarget(1.0, 0.8))
        module.stop()
        assert io.drive_volts == 0.0 and io.steer_volts == 0.0
        assert module.setpoint == ModuleTarget(0.0, 0.8)


class TestHealth:
    def test_healthy_when_seeded_and_answering(self):
        module, _, _ = seeded_module()
        assert module.healthy

    def test_unhealthy_when_a_motor_controller_stops_answering(self):
        module, io, _ = seeded_module()
        io.connected = False
        module.periodic(disabled=False)
        assert not module.healthy


class TestSetAngle:
    def test_points_the_wheel_without_rolling(self):
        module, io, _ = seeded_module(0.0)
        module.set_angle(0.8)
        assert io.steer_target == pytest.approx(0.8)
        assert io.drive_velocity == 0.0
        assert module.setpoint == ModuleTarget(0.0, 0.8)

    def test_takes_the_short_way(self):
        module, io, _ = seeded_module(0.0)
        module.set_angle(math.radians(135))
        assert io.steer_target == pytest.approx(math.radians(-45))

    def test_unseeded_module_stays_stopped(self):
        module, io, _ = make_module(encoder_connected=False)
        module.periodic(disabled=False)
        module.set_angle(0.8)
        assert io.drive_volts == 0.0 and io.steer_volts == 0.0
