"""
Tests for the simulated drivetrain IO (milestone M2).

Generated by Claude. The M2 "done" check is here: a single simulated module
tracks steer angle and drive speed commands. The other tests check the
failure options (latency, boot delay, gear mismatch) behave as documented,
because later milestones rely on them to test the module code.
"""

import doctest
import importlib
import math

import ntcore
import pytest

from config.module_presets import MK4I_L3
from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain.io.abs_encoder_io import AbsoluteEncoderInputs
from subsystem.drivetrain.io.abs_encoder_sim import AbsoluteEncoderIOSim
from subsystem.drivetrain.io.gyro_io import GyroInputs
from subsystem.drivetrain.io.gyro_io_sim import GyroIOSim
from subsystem.drivetrain.io.module_io import ModuleInputs, ModuleIO
from subsystem.drivetrain.io.module_io_sim import ModuleIOSim, ModuleSimOptions
from utils.inputs_publisher import InputsPublisher

LOOP_S = 0.02


def run(io, inputs, seconds):
    """Run the sim for a number of seconds of 20 ms loops."""
    for _ in range(round(seconds / LOOP_S)):
        io.update_inputs(inputs)


class TestModuleTracksCommands:
    """M2 done check: one simulated module follows angle and speed commands."""

    def test_is_a_module_io(self):
        assert isinstance(ModuleIOSim(CONFIG), ModuleIO)

    @pytest.mark.parametrize("target", [0.5, -1.2, math.pi / 2, 3.0])
    def test_steer_reaches_angle(self, target):
        io, inputs = ModuleIOSim(CONFIG), ModuleInputs()
        io.set_steer_angle(target)
        run(io, inputs, 0.5)
        error = math.remainder(inputs.steer_angle_rad - target, math.tau)
        assert abs(error) < math.radians(1.0)
        assert abs(inputs.steer_velocity_rad_per_s) < 0.1

    def test_steer_takes_short_way_around(self):
        io, inputs = ModuleIOSim(CONFIG), ModuleInputs()
        io.set_steer_angle(math.radians(170))
        run(io, inputs, 0.5)
        io.set_steer_angle(math.radians(-170))
        io.update_inputs(inputs)
        # Short way from 170 to -170 degrees is counterclockwise (positive).
        assert inputs.steer_velocity_rad_per_s > 0
        run(io, inputs, 0.5)
        assert abs(math.remainder(inputs.steer_angle_rad - math.radians(-170), math.tau)) < math.radians(1.0)

    @pytest.mark.parametrize("target", [1.0, 3.0, -2.0])
    def test_drive_reaches_speed(self, target):
        io, inputs = ModuleIOSim(CONFIG), ModuleInputs()
        # Feedforward of kV * speed, as the module code will send it.
        ff = 12.0 / CONFIG.free_speed_mps * target
        io.set_drive_velocity(target, ff)
        run(io, inputs, 1.0)
        assert inputs.drive_velocity_mps == pytest.approx(target, abs=0.05)

    def test_drive_position_adds_up_speed(self):
        io, inputs = ModuleIOSim(CONFIG), ModuleInputs()
        io.set_drive_velocity(2.0, 12.0 / CONFIG.free_speed_mps * 2.0)
        run(io, inputs, 1.0)
        start = inputs.drive_position_m
        run(io, inputs, 1.0)
        assert inputs.drive_position_m - start == pytest.approx(2.0, abs=0.05)

    def test_voltage_mode_and_stop(self):
        io, inputs = ModuleIOSim(CONFIG), ModuleInputs()
        io.set_drive_voltage(6.0)
        run(io, inputs, 1.0)
        # Half voltage gives about half the free speed.
        assert inputs.drive_velocity_mps == pytest.approx(CONFIG.free_speed_mps / 2, rel=0.02)
        assert inputs.drive_applied_volts == pytest.approx(6.0)
        assert inputs.drive_current_amps > 0
        io.stop()
        run(io, inputs, 1.5)
        assert abs(inputs.drive_velocity_mps) < 0.01

    def test_voltage_is_limited_to_12v(self):
        io, inputs = ModuleIOSim(CONFIG), ModuleInputs()
        io.set_steer_voltage(40.0)
        io.update_inputs(inputs)
        assert inputs.steer_applied_volts == pytest.approx(12.0)


class TestSteerSeeding:
    def test_steer_encoder_reads_zero_at_boot(self):
        io = ModuleIOSim(CONFIG, ModuleSimOptions(initial_steer_angle_rad=1.0))
        inputs = ModuleInputs()
        io.update_inputs(inputs)
        assert inputs.steer_angle_rad == pytest.approx(0.0)
        assert io.true_steer_angle_rad == pytest.approx(1.0)

    def test_seeding_from_absolute_encoder_lines_up(self):
        corner = CONFIG.corners[1]
        io = ModuleIOSim(CONFIG, ModuleSimOptions(initial_steer_angle_rad=-2.0))
        encoder = AbsoluteEncoderIOSim.for_module(io, corner)
        enc_inputs, inputs = AbsoluteEncoderInputs(), ModuleInputs()
        encoder.update_inputs(enc_inputs)
        assert enc_inputs.connected
        io.reset_steer_angle(enc_inputs.angle_rad)
        io.update_inputs(inputs)
        assert inputs.steer_angle_rad == pytest.approx(-2.0, abs=1e-6)
        # After seeding, commands point the real wheel where asked.
        io.set_steer_angle(0.0)
        run(io, inputs, 0.5)
        assert abs(io.true_steer_angle_rad) < math.radians(1.0)


class TestAbsoluteEncoderSim:
    def test_raw_plus_offset_is_true_angle(self):
        encoder = AbsoluteEncoderIOSim(lambda: 0.5, offset_rot=0.2)
        inputs = AbsoluteEncoderInputs()
        encoder.update_inputs(inputs)
        assert inputs.raw_rot == pytest.approx(0.5 / math.tau - 0.2)
        assert inputs.angle_rad == pytest.approx(0.5)

    def test_offset_error_shifts_angle(self):
        encoder = AbsoluteEncoderIOSim(lambda: 0.0, offset_rot=0.1, offset_error_rot=0.01)
        inputs = AbsoluteEncoderInputs()
        encoder.update_inputs(inputs)
        assert inputs.angle_rad == pytest.approx(0.01 * math.tau)

    def test_never_connects(self):
        encoder = AbsoluteEncoderIOSim(lambda: 1.0, offset_rot=0.0, never_connects=True)
        inputs = AbsoluteEncoderInputs()
        for _ in range(50):
            encoder.update_inputs(inputs)
            assert not inputs.connected

    def test_latency(self):
        angle = [0.0]
        encoder = AbsoluteEncoderIOSim(lambda: angle[0], offset_rot=0.0, latency_loops=2)
        inputs = AbsoluteEncoderInputs()
        readings = []
        for i in range(4):
            angle[0] = 0.1 * i
            encoder.update_inputs(inputs)
            readings.append(round(inputs.angle_rad, 6) if inputs.connected else None)
        assert readings == [None, None, 0.0, 0.1]


class TestModuleSimOptions:
    def test_latency_delays_readings(self):
        io = ModuleIOSim(CONFIG, ModuleSimOptions(latency_loops=3))
        inputs = ModuleInputs()
        io.set_drive_voltage(12.0)
        for _ in range(3):
            io.update_inputs(inputs)
            assert inputs.drive_velocity_mps == 0.0
        io.update_inputs(inputs)
        assert inputs.drive_velocity_mps > 0.0

    def test_gear_mismatch_shows_in_ground_truth(self):
        # Config says L2, but L3 gears are really installed: the robot goes
        # farther than the encoder reports, by 6.75 / 6.12.
        io = ModuleIOSim(CONFIG, ModuleSimOptions(actual_preset=MK4I_L3))
        inputs = ModuleInputs()
        io.set_drive_voltage(6.0)
        run(io, inputs, 1.0)
        assert io.true_drive_position_m / inputs.drive_position_m == pytest.approx(6.75 / 6.12)

    def test_worn_wheel_shows_in_ground_truth(self):
        io = ModuleIOSim(CONFIG, ModuleSimOptions(actual_wheel_radius_m=0.049))
        inputs = ModuleInputs()
        io.set_drive_voltage(6.0)
        run(io, inputs, 1.0)
        assert io.true_drive_position_m / inputs.drive_position_m == pytest.approx(0.049 / CONFIG.wheel_radius_m)


class TestGyroSim:
    def test_integrates_rate(self):
        gyro, inputs = GyroIOSim(), GyroInputs()
        for _ in range(50):
            gyro.step(1.0, LOOP_S)
        gyro.update_inputs(inputs)
        assert inputs.connected
        assert inputs.yaw_rad == pytest.approx(1.0)
        assert inputs.yaw_rate_rad_per_s == pytest.approx(1.0)

    def test_yaw_keeps_counting_past_a_turn(self):
        gyro, inputs = GyroIOSim(), GyroInputs()
        gyro.step(1.0, 2 * math.tau)
        gyro.update_inputs(inputs)
        assert inputs.yaw_rad == pytest.approx(2 * math.tau)

    def test_boot_delay(self):
        gyro, inputs = GyroIOSim(boot_delay_loops=2), GyroInputs()
        states = []
        for _ in range(3):
            gyro.update_inputs(inputs)
            states.append(inputs.connected)
        assert states == [False, False, True]

    def test_drift_is_not_in_true_yaw(self):
        gyro, inputs = GyroIOSim(drift_rad_per_s=0.001), GyroInputs()
        gyro.step(0.0, 60.0)
        gyro.update_inputs(inputs)
        assert inputs.yaw_rad == pytest.approx(0.06)
        assert gyro.true_yaw_rad == 0.0


class TestInputsPublisher:
    def test_publishes_module_inputs(self):
        inst = ntcore.NetworkTableInstance.create()
        try:
            publisher = InputsPublisher("/Drive/Module/frontLeft", ModuleInputs, inst=inst)
            subs = {
                "drive_velocity_mps": inst.getDoubleTopic("/Drive/Module/frontLeft/drive_velocity_mps").subscribe(-1.0),
                "steer_connected": inst.getBooleanTopic("/Drive/Module/frontLeft/steer_connected").subscribe(True),
            }
            publisher.publish(ModuleInputs(drive_velocity_mps=2.5, steer_connected=False))
            assert subs["drive_velocity_mps"].get() == 2.5
            assert subs["steer_connected"].get() is False
        finally:
            ntcore.NetworkTableInstance.destroy(inst)

    def test_rejects_unsupported_field(self):
        from dataclasses import dataclass

        @dataclass
        class Bad:
            name: str = ""

        inst = ntcore.NetworkTableInstance.create()
        try:
            with pytest.raises(TypeError, match="can't publish"):
                InputsPublisher("/Bad", Bad, inst=inst)
        finally:
            ntcore.NetworkTableInstance.destroy(inst)


@pytest.mark.parametrize(
    "module_name",
    [
        "subsystem.drivetrain.io.module_io",
        "subsystem.drivetrain.io.module_io_sim",
        "subsystem.drivetrain.io.sim_motor",
        "subsystem.drivetrain.io.abs_encoder_io",
        "subsystem.drivetrain.io.abs_encoder_sim",
        "subsystem.drivetrain.io.gyro_io",
        "subsystem.drivetrain.io.gyro_io_sim",
        "utils.inputs_publisher",
    ],
)
def test_docstring_examples(module_name):
    """The examples in the IO docstrings are run here so they stay correct."""
    result = doctest.testmod(importlib.import_module(module_name), optionflags=doctest.ELLIPSIS)
    assert result.attempted > 0
    assert result.failed == 0
