"""
Tests for swerve characterization: drive and steer SysId, wheel radius, steer step test, offsets.

Generated by Claude. Everything runs on the simulated drivetrain, whose
motors have known kV and kA, so the tests can check the tools measure the
right numbers before anyone runs them on the robot.
"""

import dataclasses
import doctest
import importlib
import math

import commands2
import pytest
from wpilib.simulation import DriverStationSim, pauseTiming, resumeTiming, stepTiming

from commands.drive.calibrate_offsets import CalibrateOffsets, offsets_from_raw
from commands.drive.characterization import SteerStepTest, WheelRadiusCharacterization, register_swerve
from config.robot_config import DriveFeedforward, wrap_rotations
from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain.drivetrain_sim import DrivetrainSim
from subsystem.drivetrain.io.module_io_sim import ModuleSimOptions
from utils.sysid.chooser import CharacterizationChooser


@pytest.fixture
def scheduler():
    """A command scheduler with the robot enabled, and simulated time we step by hand."""
    pauseTiming()
    DriverStationSim.setEnabled(True)
    DriverStationSim.notifyNewData()
    commands2.CommandScheduler.resetInstance()
    yield commands2.CommandScheduler.getInstance()
    commands2.CommandScheduler.getInstance().cancelAll()
    commands2.CommandScheduler.resetInstance()
    DriverStationSim.resetData()
    DriverStationSim.notifyNewData()
    resumeTiming()


def loops(scheduler, seconds):
    for _ in range(round(seconds / 0.02)):
        stepTiming(0.02)
        scheduler.run()


def run_until_done(scheduler, command, max_s=60.0):
    """Schedule ``command`` and run 20 ms loops until it finishes. Returns the seconds it took."""
    command.schedule()
    count = 0
    while scheduler.isScheduled(command) and count < max_s / 0.02:
        stepTiming(0.02)
        scheduler.run()
        count += 1
    return count * 0.02


def make_sim(scheduler, config=CONFIG, **options):
    """A seeded simulated drivetrain whose periodic() the scheduler runs."""
    sim = DrivetrainSim(config, **options)
    loops(scheduler, 0.2)
    return sim


class TestDriveSysId:
    def test_measures_the_simulated_drive_motors(self, scheduler):
        sim = make_sim(scheduler)
        tests = register_swerve(CharacterizationChooser("none", commands2.InstantCommand()), sim.drivetrain)
        run_until_done(scheduler, tests["drive"].all_tests())
        io = sim.module_sims[0]
        # The sim motor's kV and kA are per motor rotation; SysId's are per meter.
        expected_kv = io._drive.kv / io._drive_m_per_rot
        expected_ka = io._drive.ka / io._drive_m_per_rot
        fit = tests["drive"].estimate
        assert fit is not None
        assert fit.kv == pytest.approx(expected_kv, rel=0.03)
        assert fit.ka == pytest.approx(expected_ka, rel=0.1)
        assert abs(fit.ks) < 0.05  # the sim has no friction

    def test_wheels_point_straight_and_robot_drives_forward(self, scheduler):
        sim = make_sim(scheduler)
        tests = register_swerve(CharacterizationChooser("none", commands2.InstantCommand()), sim.drivetrain)
        run_until_done(scheduler, tests["drive"].quasistatic(forward=True))
        assert sim.true_pose.x_m > 1.0
        assert abs(sim.true_pose.y_m) < 0.01
        assert abs(sim.true_pose.heading_rad) < math.radians(0.5)
        for io in sim.module_sims:
            assert abs(math.remainder(io.true_steer_angle_rad, math.tau)) < math.radians(1)

    def test_forward_then_reverse_comes_back(self, scheduler):
        sim = make_sim(scheduler)
        tests = register_swerve(CharacterizationChooser("none", commands2.InstantCommand()), sim.drivetrain)
        run_until_done(scheduler, tests["drive"].all_tests())
        assert abs(sim.true_pose.x_m) < 0.5


class TestSteerSysId:
    def test_measures_the_simulated_steer_motors(self, scheduler):
        sim = make_sim(scheduler)
        tests = register_swerve(CharacterizationChooser("none", commands2.InstantCommand()), sim.drivetrain)
        run_until_done(scheduler, tests["steer"].all_tests())
        io = sim.module_sims[0]
        fit = tests["steer"].estimate
        assert fit is not None
        # kA is too small to measure well at 50 Hz (the steer motor reaches
        # full speed within a loop), so only kV is checked.
        assert fit.kv == pytest.approx(io._steer.kv / io._steer_rad_per_rot, rel=0.03)

    def test_drive_motors_stay_off(self, scheduler):
        sim = make_sim(scheduler)
        tests = register_swerve(CharacterizationChooser("none", commands2.InstantCommand()), sim.drivetrain)
        run_until_done(scheduler, tests["steer"].dynamic(forward=True))
        assert math.hypot(sim.true_pose.x_m, sim.true_pose.y_m) < 0.01


class TestMeasuredFeedforwardInTheSim:
    def test_sim_uses_measured_drive_numbers(self):
        config = dataclasses.replace(CONFIG, drive_feedforward=DriveFeedforward(0.1, 2.5, 0.6))
        io = DrivetrainSim(config).module_sims[0]
        assert io._drive.kv / io._drive_m_per_rot == pytest.approx(2.5)
        assert io._drive.ka / io._drive_m_per_rot == pytest.approx(0.6)
        assert io._drive.ks == pytest.approx(0.1)


class TestWheelRadius:
    @pytest.mark.parametrize("real_radius_m", [0.0508, 0.0490])
    def test_finds_the_real_wheel_radius(self, scheduler, real_radius_m):
        options = {c.name: ModuleSimOptions(actual_wheel_radius_m=real_radius_m) for c in CONFIG.corners}
        sim = make_sim(scheduler, module_options=options)
        command = WheelRadiusCharacterization(sim.drivetrain)
        run_until_done(scheduler, command)
        assert command.radius_m == pytest.approx(real_radius_m, rel=0.005)

    def test_stopped_early_gives_no_answer(self, scheduler):
        sim = make_sim(scheduler)
        command = WheelRadiusCharacterization(sim.drivetrain)
        command.schedule()
        loops(scheduler, 1.0)
        command.cancel()
        assert command.radius_m is None


class TestSteerStep:
    def test_reports_settle_time_and_overshoot_for_every_corner(self, scheduler):
        sim = make_sim(scheduler)
        command = SteerStepTest(sim.drivetrain)
        run_until_done(scheduler, command)
        assert set(command.settle_time_s) == {c.name for c in CONFIG.corners}
        for name in command.settle_time_s:
            assert 0.0 < command.settle_time_s[name] < SteerStepTest.STEP_S
            assert 0.0 <= command.overshoot_deg[name] < 20.0

    def test_a_slow_steer_loop_settles_later(self, scheduler):
        fast = SteerStepTest(make_sim(scheduler).drivetrain)
        run_until_done(scheduler, fast)
        slow_options = {c.name: ModuleSimOptions(steer_kp=8.0) for c in CONFIG.corners}
        slow = SteerStepTest(make_sim(scheduler, module_options=slow_options).drivetrain)
        run_until_done(scheduler, slow)
        assert slow.settle_time_s["frontLeft"] > fast.settle_time_s["frontLeft"]


class TestCalibrateOffsets:
    def test_new_offsets_make_forward_read_zero(self, scheduler):
        errors = {"frontLeft": 0.02, "frontRight": -0.1, "backLeft": 0.3, "backRight": 0.0}
        sim = make_sim(scheduler, encoder_options={name: {"offset_error_rot": e} for name, e in errors.items()})
        # The sim wheels start pointing straight forward, as if lined up by hand.
        command = CalibrateOffsets(sim.drivetrain)
        command.initialize()
        assert command.offsets_rot is not None
        for corner, offset in zip(CONFIG.corners, command.offsets_rot):
            assert offset == pytest.approx(wrap_rotations(corner.encoder_offset_rot - errors[corner.name]))
            assert -0.5 <= offset < 0.5

    def test_works_while_disabled(self):
        assert CalibrateOffsets(DrivetrainSim(CONFIG).drivetrain).runsWhenDisabled()

    def test_refuses_when_an_encoder_is_missing(self, scheduler):
        sim = make_sim(scheduler, encoder_options={"backLeft": {"never_connects": True}})
        command = CalibrateOffsets(sim.drivetrain)
        command.initialize()
        assert command.offsets_rot is None

    def test_offsets_wrap(self):
        assert offsets_from_raw([0.75, -0.75, 0.5, 0.0]) == (0.25, -0.25, -0.5, 0.0)


@pytest.mark.parametrize("module_name", ["commands.drive.characterization", "commands.drive.calibrate_offsets"])
def test_docstring_examples(module_name):
    result = doctest.testmod(importlib.import_module(module_name), optionflags=doctest.ELLIPSIS)
    assert result.attempted > 0
    assert result.failed == 0
