"""
Tests for the swerve math, the module logic and the drivetrain (milestone M3).

Generated by Claude. The M3 "done" checks are here:
- driving straight (field-relative) while rotating doesn't drift off the line,
  and odometry matches where the simulated robot really is;
- an absolute encoder that never answers flags its module.
"""

import doctest
import importlib
import math

import pytest

from config.module_presets import MK4I_L3
from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain import drivetrain as drivetrain_module
from subsystem.drivetrain.drivetrain_sim import DrivetrainSim
from subsystem.drivetrain.io.gyro_io_sim import GyroIOSim
from subsystem.drivetrain.io.module_io_sim import ModuleSimOptions
from subsystem.drivetrain.module import SEED_TIMEOUT_LOOPS
from subsystem.drivetrain.swerve_math import (
    ChassisSpeeds,
    ModuleTarget,
    cosine_scale,
    desaturate,
    discretize,
    field_to_robot,
    forward_kinematics,
    inverse_kinematics,
    optimize,
)
from utils.wpimath_compat import Pose2d, Rotation2d

CORNERS = [(c.x_m, c.y_m) for c in CONFIG.corners]


def run(sim, seconds, speeds=None, field_relative=True):
    """Run the simulated drivetrain for some seconds, driving with `speeds` if given."""
    drive = sim.drivetrain
    for _ in range(round(seconds / 0.02)):
        drive.periodic()
        if speeds is not None:
            drive.drive(speeds, field_relative=field_relative)


def angle_error(a, b):
    return abs(math.remainder(a - b, math.tau))


class TestSwerveMath:
    @pytest.mark.parametrize(
        "speeds",
        [ChassisSpeeds(1, 0, 0), ChassisSpeeds(0, -2, 0), ChassisSpeeds(0, 0, 3), ChassisSpeeds(1.2, -0.4, 1.7)],
    )
    def test_kinematics_round_trip(self, speeds):
        back = forward_kinematics(inverse_kinematics(speeds, CORNERS), CORNERS)
        assert back.vx_mps == pytest.approx(speeds.vx_mps, abs=1e-9)
        assert back.vy_mps == pytest.approx(speeds.vy_mps, abs=1e-9)
        assert back.omega_rad_per_s == pytest.approx(speeds.omega_rad_per_s, abs=1e-9)

    def test_spin_in_place_wheel_speed_is_omega_times_radius(self):
        targets = inverse_kinematics(ChassisSpeeds(0, 0, 2.0), CORNERS)
        for t in targets:
            assert t.speed_mps == pytest.approx(2.0 * CONFIG.drive_base_radius_m)

    def test_discretize_matches_wpilib(self):
        # WPILib's ChassisSpeeds.discretize does the same math (checked on 2026).
        try:
            from wpimath.kinematics import ChassisSpeeds as WpiSpeeds
        except ImportError:
            pytest.skip("2027 renamed ChassisSpeeds; the 2026 run covers this")
        ours = discretize(ChassisSpeeds(1.5, -0.5, 2.5), 0.02)
        theirs = WpiSpeeds.discretize(1.5, -0.5, 2.5, 0.02)
        assert ours.vx_mps == pytest.approx(theirs.vx)
        assert ours.vy_mps == pytest.approx(theirs.vy)
        assert ours.omega_rad_per_s == pytest.approx(theirs.omega)

    def test_field_to_robot_round_trip(self):
        s = field_to_robot(field_to_robot(ChassisSpeeds(1, 2, 3), 0.7), -0.7)
        assert (s.vx_mps, s.vy_mps, s.omega_rad_per_s) == pytest.approx((1, 2, 3))

    def test_desaturate_keeps_direction(self):
        targets = inverse_kinematics(ChassisSpeeds(4.0, 0.0, 6.0), CORNERS)
        out = desaturate(targets, 4.0)
        assert max(t.speed_mps for t in out) == pytest.approx(4.0)
        ratios = {round(o.speed_mps / t.speed_mps, 9) for o, t in zip(out, targets)}
        assert len(ratios) == 1

    @pytest.mark.parametrize("target_deg, current_deg", [(170, 0), (-100, 0), (0, 179), (45, -135)])
    def test_optimize_never_turns_more_than_90(self, target_deg, current_deg):
        target = ModuleTarget(1.0, math.radians(target_deg))
        out = optimize(target, math.radians(current_deg))
        assert angle_error(out.angle_rad, math.radians(current_deg)) <= math.pi / 2 + 1e-9
        # Same wheel motion either way: speed vector unchanged.
        assert out.speed_mps * math.cos(out.angle_rad) == pytest.approx(math.cos(target.angle_rad))
        assert out.speed_mps * math.sin(out.angle_rad) == pytest.approx(math.sin(target.angle_rad))

    def test_cosine_scale(self):
        assert cosine_scale(ModuleTarget(2.0, 0.0), math.pi / 2).speed_mps == pytest.approx(0.0, abs=1e-12)


class TestDriftWhileRotating:
    """M3 done check: field-relative straight line while spinning."""

    SPEEDS = ChassisSpeeds(vx_mps=1.5, vy_mps=0.0, omega_rad_per_s=2.0)

    def test_stays_on_line_and_odometry_matches_truth(self):
        sim = DrivetrainSim(CONFIG)
        run(sim, 3.0, self.SPEEDS)
        truth = sim.true_pose
        assert truth.x_m > 4.0  # it really drove about 4.4 m
        assert abs(truth.y_m) < 0.10  # and stayed within 10 cm of the line
        pose = sim.drivetrain.pose
        assert math.hypot(pose.X() - truth.x_m, pose.Y() - truth.y_m) < 0.01
        assert angle_error(pose.rotation().radians(), truth.heading_rad) < math.radians(0.5)

    def test_discretize_reduces_drift(self, monkeypatch):
        with_disc = DrivetrainSim(CONFIG)
        run(with_disc, 3.0, self.SPEEDS)
        monkeypatch.setattr(drivetrain_module, "discretize", lambda s, dt: s)
        without = DrivetrainSim(CONFIG)
        run(without, 3.0, self.SPEEDS)
        assert abs(with_disc.true_pose.y_m) < abs(without.true_pose.y_m)

    def test_straight_line_without_rotation(self):
        sim = DrivetrainSim(CONFIG)
        run(sim, 2.0, ChassisSpeeds(2.0, 0.0, 0.0))
        assert abs(sim.true_pose.y_m) < 0.005
        assert abs(sim.true_pose.heading_rad) < math.radians(0.5)

    def test_wrong_gears_make_odometry_drift(self):
        # Config says L2, the modules really have L3: odometry under-reads.
        options = {c.name: ModuleSimOptions(actual_preset=MK4I_L3) for c in CONFIG.corners}
        sim = DrivetrainSim(CONFIG, module_options=options)
        run(sim, 2.0, ChassisSpeeds(1.0, 0.0, 0.0))
        assert sim.true_pose.x_m / sim.drivetrain.pose.X() == pytest.approx(6.75 / 6.12, rel=0.01)


class TestSeedingAndHealth:
    def test_wheels_seeded_from_absolute_encoders(self):
        angles = [0.3, -1.0, 2.5, -2.9]
        options = {c.name: ModuleSimOptions(initial_steer_angle_rad=a) for c, a in zip(CONFIG.corners, angles)}
        sim = DrivetrainSim(CONFIG, module_options=options)
        run(sim, 0.04)
        for module, angle in zip(sim.drivetrain.modules, angles):
            assert module.seeded
            assert module.angle_rad == pytest.approx(angle, abs=1e-6)
        # Driving forward points every real wheel forward (or backward, after optimize).
        run(sim, 0.5, ChassisSpeeds(1.0, 0.0, 0.0), field_relative=False)
        for io in sim.module_sims:
            assert angle_error(io.true_steer_angle_rad, 0.0) < math.radians(1) or angle_error(
                io.true_steer_angle_rad, math.pi
            ) < math.radians(1)

    def test_encoder_boot_failure_flags_module(self):
        """M3 done check: a dead absolute encoder flags its module and that wheel stays stopped."""
        sim = DrivetrainSim(CONFIG, encoder_options={"backLeft": {"never_connects": True}})
        run(sim, (SEED_TIMEOUT_LOOPS + 5) * 0.02, ChassisSpeeds(1.0, 0.0, 0.0))
        flags = {m.corner.name: m.encoder_failed for m in sim.drivetrain.modules}
        assert flags == {"frontLeft": False, "frontRight": False, "backLeft": True, "backRight": False}
        assert not sim.drivetrain.all_modules_healthy
        back_left = sim.drivetrain.modules[2]
        assert back_left.inputs.drive_applied_volts == 0.0
        assert back_left.inputs.steer_applied_volts == 0.0

    def test_slow_encoder_seeds_late_without_flag(self):
        sim = DrivetrainSim(CONFIG, encoder_options={"frontRight": {"boot_delay_loops": 10}})
        run(sim, 0.1)
        assert not sim.drivetrain.modules[1].seeded
        run(sim, 0.2)
        assert sim.drivetrain.modules[1].seeded
        assert not sim.drivetrain.modules[1].encoder_failed

    def test_reseed_while_disabled_after_slip(self):
        sim = DrivetrainSim(CONFIG)
        run(sim, 0.1)
        module, io = sim.drivetrain.modules[0], sim.module_sims[0]
        io.reset_steer_angle(module.angle_rad + math.radians(10))  # steer encoder jumps 10 degrees
        run(sim, 0.06)
        assert module.reseed_count == 1
        assert angle_error(module.angle_rad, io.true_steer_angle_rad) < math.radians(0.5)

    def test_stopped_wheel_keeps_its_angle(self):
        sim = DrivetrainSim(CONFIG)
        run(sim, 0.5, ChassisSpeeds(0.0, 1.0, 0.0), field_relative=False)  # wheels point left
        run(sim, 0.5, ChassisSpeeds(), field_relative=False)
        for io in sim.module_sims:
            assert angle_error(io.true_steer_angle_rad, math.pi / 2) < math.radians(1) or angle_error(
                io.true_steer_angle_rad, -math.pi / 2
            ) < math.radians(1)


class TestHeading:
    def test_gyro_dropout_keeps_heading_continuous(self):
        gyro = GyroIOSim()
        sim = DrivetrainSim(CONFIG, gyro=gyro)
        run(sim, 1.0, ChassisSpeeds(0, 0, 1.0))
        gyro._never_connects = True  # gyro unplugged mid-match
        run(sim, 1.0, ChassisSpeeds(0, 0, 1.0))
        assert angle_error(sim.drivetrain.heading_rad, sim.true_pose.heading_rad) < math.radians(3)
        gyro._never_connects = False  # and back
        run(sim, 0.5, ChassisSpeeds(0, 0, 1.0))
        assert angle_error(sim.drivetrain.heading_rad, sim.true_pose.heading_rad) < math.radians(3)

    def test_reset_pose(self):
        sim = DrivetrainSim(CONFIG)
        run(sim, 0.5, ChassisSpeeds(1.0, 0, 0.5))
        sim.drivetrain.reset_pose(Pose2d(3.0, 2.0, Rotation2d(math.pi)))
        run(sim, 0.02)
        pose = sim.drivetrain.pose
        assert (pose.X(), pose.Y()) == pytest.approx((3.0, 2.0), abs=0.05)
        assert angle_error(pose.rotation().radians(), math.pi) < math.radians(2)


@pytest.mark.parametrize(
    "module_name",
    [
        "subsystem.drivetrain.swerve_math",
        "subsystem.drivetrain.module",
        "subsystem.drivetrain.drivetrain",
        "subsystem.drivetrain.drivetrain_sim",
        "utils.wpimath_compat",
        "utils.alerts",
        "config.robot_config",
    ],
)
def test_docstring_examples(module_name):
    """The examples in the docstrings are run here so they stay correct."""
    result = doctest.testmod(importlib.import_module(module_name), optionflags=doctest.ELLIPSIS)
    assert result.attempted > 0
    assert result.failed == 0
