"""
Config sanity tests for swerve module presets and robot configs.

Generated by Claude. These run on every PR so a bad offset, a duplicate CAN
ID or a wrong gear ratio fails CI instead of showing up on the field.
"""

import dataclasses
import math

import ntcore
import pytest

from config import loader
from config.module_presets import (
    DEFAULT_PRESET,
    MK4I_L2,
    NEO,
    NOMINAL_WHEEL_RADIUS_M,
    PRESETS,
)
from config.robot_config import CORNER_NAMES, wrap_rotations

# SDS published ratios: (drive, steer). Source: SDS MK4i / MK4 product pages.
SDS_RATIOS = {
    "MK4i_L1": (8.14, 150 / 7),
    "MK4i_L2": (6.75, 150 / 7),
    "MK4i_L3": (6.12, 150 / 7),
    "MK4_L1": (8.14, 12.8),
    "MK4_L2": (6.75, 12.8),
    "MK4_L3": (6.12, 12.8),
    "MK4_L4": (5.14, 12.8),
}

# Theoretical NEO free speed on a 4 in wheel, m/s (research doc section 1).
FREE_SPEED_MPS = {
    "MK4i_L1": 3.71,
    "MK4i_L2": 4.47,
    "MK4i_L3": 4.93,
    "MK4_L4": 5.87,
}

ROBOT_CONFIGS = list(loader.ROBOTS.values())
RESERVED_TEST_CAN_IDS = range(15, 20)


class TestModulePresets:
    def test_default_is_mk4i_l2(self):
        assert DEFAULT_PRESET is MK4I_L2

    def test_every_preset_matches_sds(self):
        assert set(PRESETS) == set(SDS_RATIOS)
        for name, (drive, steer) in SDS_RATIOS.items():
            preset = PRESETS[name]
            assert preset.drive_ratio == pytest.approx(drive)
            assert preset.steer_ratio == pytest.approx(steer)

    @pytest.mark.parametrize("name", sorted(SDS_RATIOS))
    def test_wheel_travel_per_motor_rotation(self, name):
        preset = PRESETS[name]
        drive, steer = SDS_RATIOS[name]
        r = NOMINAL_WHEEL_RADIUS_M
        # One wheel turn takes `drive` motor turns and covers 2*pi*r.
        assert preset.drive_m_per_motor_rot(r) * drive == pytest.approx(2 * math.pi * r)
        assert preset.steer_rad_per_motor_rot * steer == pytest.approx(2 * math.pi)

    @pytest.mark.parametrize("name", sorted(FREE_SPEED_MPS))
    def test_free_speed(self, name):
        speed = PRESETS[name].free_speed_mps(NEO, NOMINAL_WHEEL_RADIUS_M)
        assert speed == pytest.approx(FREE_SPEED_MPS[name], abs=0.01)

    def test_steer_direction_by_module_type(self):
        # MK4i steers in the opposite direction to the MK4.
        for name, preset in PRESETS.items():
            assert preset.steer_inverted == name.startswith("MK4i")

    def test_presets_are_frozen(self):
        with pytest.raises(dataclasses.FrozenInstanceError):
            MK4I_L2.drive_ratio = 6.12  # type: ignore[misc]


@pytest.mark.parametrize("cfg", ROBOT_CONFIGS, ids=lambda c: c.name)
class TestRobotConfigs:
    def test_preset_is_known(self, cfg):
        assert PRESETS[cfg.preset.name] is cfg.preset

    def test_corner_order_and_positions(self, cfg):
        assert tuple(c.name for c in cfg.corners) == CORNER_NAMES
        fl, fr, bl, br = cfg.corners
        assert fl.x_m > 0 and fl.y_m > 0
        assert fr.x_m > 0 and fr.y_m < 0
        assert bl.x_m < 0 and bl.y_m > 0
        assert br.x_m < 0 and br.y_m < 0

    def test_offsets_in_range(self, cfg):
        for c in cfg.corners:
            assert -0.5 <= c.encoder_offset_rot < 0.5, c.name

    def test_can_ids_unique_and_allowed(self, cfg):
        ids = cfg.all_can_ids()
        assert len(ids) == len(set(ids))
        for i in ids:
            assert 1 <= i <= 62
            assert i not in RESERVED_TEST_CAN_IDS

    def test_drivetrain_can_ids_follow_convention(self, cfg):
        # Modules start at 50, 3 consecutive IDs each: drive, steer, encoder.
        for i, c in enumerate(cfg.corners):
            base = 50 + 3 * i
            assert c.can_ids == (base, base + 1, base + 2), c.name

    def test_wheel_radius_plausible(self, cfg):
        # Worn 4 in tread is a little under 2 in; anything far off is a typo.
        assert 0.045 < cfg.wheel_radius_m < 0.053

    def test_derived_limits_positive(self, cfg):
        assert cfg.free_speed_mps > 0
        assert cfg.max_angular_speed_rad_per_s > 0


class TestSwerveTestBot:
    def test_matches_robot_2026(self):
        cfg = loader.ROBOTS["swerve_test_bot"]
        assert cfg.preset is MK4I_L2
        assert cfg.drive_base_radius_m == pytest.approx(0.390, abs=0.001)
        offsets = [c.encoder_offset_rot for c in cfg.corners]
        expected = [10.283203125, 323.6148 - 360, 347.2737188 - 360, 83.2865625]
        assert offsets == pytest.approx([d / 360 for d in expected])


class TestWrapRotations:
    @pytest.mark.parametrize(
        "rot, expected",
        [(0.0, 0.0), (0.25, 0.25), (0.75, -0.25), (-0.75, 0.25), (0.5, -0.5), (1.0, 0.0)],
    )
    def test_wrap(self, rot, expected):
        assert wrap_rotations(rot) == pytest.approx(expected)


class TestLoader:
    def test_explicit_name(self):
        assert loader.load_robot_config("swerve_test_bot").name == "swerve_test_bot"

    def test_unknown_name_raises(self):
        with pytest.raises(KeyError, match="Unknown robot"):
            loader.load_robot_config("not_a_robot")

    def test_name_from_nt(self):
        topic = ntcore.NetworkTableInstance.getDefault().getStringTopic(loader.ROBOT_NAME_TOPIC)
        assert loader.robot_name_from_nt() == loader.DEFAULT_ROBOT
        assert loader.load_robot_config().name == loader.DEFAULT_ROBOT
        assert topic.isPersistent()
        pub = topic.publish()
        try:
            pub.set("other_bot")
            assert loader.robot_name_from_nt() == "other_bot"
            with pytest.raises(KeyError):
                loader.load_robot_config()
        finally:
            pub.set(loader.DEFAULT_ROBOT)
            pub.close()
