"""
Tests for teleop driving: stick shaping, heading lock, TeleopDrive and X-lock.

Generated by Claude. TeleopDrive is driven with plain functions instead of a
controller, on the simulated drivetrain, for both alliances. The controller
itself (InputFactory and the YAML bindings) is tested in
tests/test_teleop_controller.py.
"""

import doctest
import importlib
import math

import pytest

from commands.drive.heading_lock import HeadingLock
from commands.drive.stick_shaping import VectorSlewLimiter, shape_stick
from commands.drive.teleop_drive import TeleopDrive, TeleopSettings
from commands.drive.x_lock import XLock
from config.module_presets import MK4I_L3
from config.robots.swerve_test_bot import CONFIG
from subsystem.drivetrain.drivetrain_sim import DrivetrainSim
from subsystem.drivetrain.io.module_io_sim import ModuleSimOptions


def angle_error(a, b):
    """Smallest difference between two angles, radians."""
    return abs(math.remainder(a - b, math.tau))


class Driver:
    """Pretend driver: the test sets the stick values and buttons, then calls run()."""

    def __init__(self, red=False, settings=None, module_options=None):
        self.forward = 0.0
        self.left = 0.0
        self.rotate = 0.0
        self.robot_relative = False
        self.red = red
        self.sim = DrivetrainSim(CONFIG, module_options=module_options)
        self.drive = self.sim.drivetrain
        self.teleop = TeleopDrive(
            self.drive,
            forward=lambda: self.forward,
            left=lambda: self.left,
            rotate=lambda: self.rotate,
            robot_relative=lambda: self.robot_relative,
            is_red=lambda: self.red,
            settings=settings,
        )
        self.run(0.1)  # let the modules seed
        self.teleop.initialize()

    def run(self, seconds):
        for _ in range(round(seconds / 0.02)):
            self.drive.periodic()
            self.teleop.execute()


class TestStickShaping:
    def test_inside_the_deadband_is_zero(self):
        assert shape_stick(0.06, -0.07, deadband=0.1, exponent=2.0) == (0.0, 0.0)

    def test_starts_from_zero_just_past_the_deadband(self):
        x, _ = shape_stick(0.11, 0.0, deadband=0.1, exponent=1.0)
        assert x == pytest.approx(0.01 / 0.9)

    @pytest.mark.parametrize("angle_deg", [0, 30, 45, 135, -100, 180])
    def test_keeps_the_stick_direction(self, angle_deg):
        a = math.radians(angle_deg)
        x, y = shape_stick(0.6 * math.cos(a), 0.6 * math.sin(a), deadband=0.1, exponent=2.0)
        assert math.atan2(y, x) == pytest.approx(math.atan2(math.sin(a), math.cos(a)))

    def test_corner_push_is_clipped_to_full_speed(self):
        x, y = shape_stick(1.0, 1.0, deadband=0.1, exponent=2.0)
        assert math.hypot(x, y) == pytest.approx(1.0)

    def test_exponent_one_is_linear(self):
        x, _ = shape_stick(0.55, 0.0, deadband=0.1, exponent=1.0)
        assert x == pytest.approx(0.5)


class TestVectorSlewLimiter:
    def test_diagonal_speeds_up_at_the_same_rate(self):
        slew = VectorSlewLimiter(max_accel=5.0, period_s=0.02)
        x, y = slew.calculate(3.0, 3.0)
        assert math.hypot(x, y) == pytest.approx(0.1)
        assert x == pytest.approx(y)

    def test_reaches_the_target(self):
        slew = VectorSlewLimiter(max_accel=5.0, period_s=0.02)
        for _ in range(100):
            out = slew.calculate(1.0, -1.0)
        assert out == pytest.approx((1.0, -1.0))

    def test_reset(self):
        slew = VectorSlewLimiter(max_accel=5.0, period_s=0.02)
        slew.calculate(1.0, 0.0)
        slew.reset()
        assert slew.calculate(0.0, 0.0) == (0.0, 0.0)


class TestHeadingLock:
    def test_waits_for_the_robot_to_stop_turning(self):
        lock = HeadingLock()
        assert lock.calculate(0.0, heading_rad=1.0, measured_omega_rad_per_s=2.0) == 0.0
        assert lock.target_rad is None
        lock.calculate(0.0, heading_rad=1.2, measured_omega_rad_per_s=0.1)
        assert lock.target_rad == 1.2

    def test_turns_back_toward_the_target(self):
        lock = HeadingLock(kp=5.0, max_omega_rad_per_s=6.0)
        lock.set_target(0.0)
        assert lock.calculate(0.0, heading_rad=0.1, measured_omega_rad_per_s=0.0) == pytest.approx(-0.5)

    def test_spin_rate_is_limited(self):
        lock = HeadingLock(kp=5.0, max_omega_rad_per_s=2.0)
        lock.set_target(math.pi / 2)
        assert lock.calculate(0.0, heading_rad=0.0, measured_omega_rad_per_s=0.0) == 2.0

    def test_on_target_sends_nothing(self):
        lock = HeadingLock(tolerance_rad=math.radians(1))
        lock.set_target(0.0)
        assert lock.calculate(0.0, heading_rad=math.radians(0.5), measured_omega_rad_per_s=0.0) == 0.0

    def test_takes_the_short_way_across_180_degrees(self):
        lock = HeadingLock(kp=5.0)
        lock.set_target(math.radians(179))
        omega = lock.calculate(0.0, heading_rad=math.radians(-179), measured_omega_rad_per_s=0.0)
        assert omega == pytest.approx(5.0 * math.radians(-2))

    def test_driver_turning_clears_the_target(self):
        lock = HeadingLock()
        lock.set_target(0.0)
        assert lock.calculate(1.5, heading_rad=0.0, measured_omega_rad_per_s=0.0) == 1.5
        assert lock.target_rad is None


@pytest.mark.parametrize("red", [False, True], ids=["blue", "red"])
class TestTeleopBothAlliances:
    """The done check: field-relative driving behaves the same for a blue and a red driver."""

    def test_stick_forward_moves_away_from_the_driver(self, red):
        driver = Driver(red=red)
        driver.teleop.reset_heading()  # robot faces away from the driver
        start_x = driver.drive.pose.X()
        driver.forward = 1.0
        driver.run(1.0)
        moved = driver.drive.pose.X() - start_x
        # Away from the blue wall is +x; away from the red wall is -x.
        assert (moved < -1.0) if red else (moved > 1.0)
        # Either way the robot drove toward its own front, without turning.
        assert driver.sim.true_pose.x_m > 1.0
        assert abs(driver.sim.true_pose.y_m) < 0.05

    def test_stick_left_moves_to_the_drivers_left(self, red):
        driver = Driver(red=red)
        driver.teleop.reset_heading()
        driver.left = 1.0
        driver.run(1.0)
        y = driver.drive.pose.Y()
        assert (y < -1.0) if red else (y > 1.0)

    def test_snap_turns_to_face_the_drivers_left(self, red):
        driver = Driver(red=red)
        driver.teleop.reset_heading()
        driver.teleop.snap_heading(90)
        driver.run(2.0)
        expected = math.radians(270 if red else 90)
        assert angle_error(driver.drive.heading_rad, expected) < math.radians(2)

    def test_reset_heading_while_facing_sideways(self, red):
        # Robot boots facing the driver's right, driver turns it to face away and re-zeros.
        driver = Driver(red=red)
        driver.rotate = 0.5
        driver.run(0.6)
        driver.rotate = 0.0
        driver.run(0.5)
        driver.teleop.reset_heading()
        heading_before = driver.sim.true_pose.heading_rad
        driver.forward = 1.0
        driver.run(1.0)
        # The real robot moved straight out along its own front.
        truth = driver.sim.true_pose
        assert math.atan2(truth.y_m, truth.x_m) == pytest.approx(heading_before, abs=math.radians(5))


class TestTeleopModes:
    def test_heading_lock_holds_against_a_pulling_wheel(self):
        # One wheel really has faster gears than the config says, so it pulls
        # the robot round while driving. Heading lock should hold it straight.
        options = {CONFIG.corners[0].name: ModuleSimOptions(actual_preset=MK4I_L3)}
        locked = Driver(module_options=options)
        unlocked = Driver(module_options=options, settings=TeleopSettings(heading_kp=0.0))
        for driver in (locked, unlocked):
            driver.forward = 0.8
            driver.run(2.0)
        # A wheel this far off (10% faster) turns the robot about 12 degrees in
        # 2 s on its own. The lock only pushes back in proportion to the error,
        # so a small steady error is left over against a constant pull.
        assert abs(unlocked.sim.true_pose.heading_rad) > math.radians(8)
        assert abs(locked.sim.true_pose.heading_rad) < math.radians(2)

    def test_heading_is_held_after_the_driver_stops_turning(self):
        driver = Driver()
        driver.rotate = 0.6
        driver.run(0.5)
        driver.rotate = 0.0
        driver.run(0.5)
        held = driver.teleop.heading_lock.target_rad
        assert held is not None
        driver.forward = 1.0
        driver.left = 0.5
        driver.run(2.0)
        assert angle_error(driver.drive.heading_rad, held) < math.radians(1)

    def test_robot_relative_drives_toward_the_robots_front(self):
        driver = Driver()
        driver.teleop.snap_heading(90)  # robot faces the driver's left
        driver.run(2.0)
        start = driver.drive.pose
        driver.robot_relative = True
        driver.forward = 1.0
        driver.run(1.0)
        end = driver.drive.pose
        assert end.Y() - start.Y() > 1.0  # its front points +y on the field
        assert abs(end.X() - start.X()) < 0.1

    def test_slow_mode_limits_speed(self):
        driver = Driver()
        driver.teleop.toggle_slow()
        driver.forward = 1.0
        driver.run(2.0)
        speed = driver.drive.measured_speeds.vx_mps
        slow_top = CONFIG.free_speed_mps * TeleopSettings().slow_scale
        assert 0.8 * slow_top < speed <= slow_top * 1.02
        driver.teleop.toggle_slow()
        driver.run(1.0)
        assert driver.drive.measured_speeds.vx_mps > 1.5 * slow_top

    def test_letting_go_stops_the_robot(self):
        driver = Driver()
        driver.forward = 1.0
        driver.run(1.0)
        driver.forward = 0.0
        driver.run(1.5)
        assert abs(driver.drive.measured_speeds.vx_mps) < 0.05


class TestXLock:
    def test_wheels_point_at_the_center_then_teleop_resumes(self):
        driver = Driver()
        lock = XLock(driver.drive)
        for _ in range(25):
            driver.drive.periodic()
            lock.execute()
        for module, corner in zip(driver.drive.modules, CONFIG.corners):
            toward_center = math.atan2(corner.y_m, corner.x_m)
            # Pointing in or out along the same line both make the X.
            assert min(
                angle_error(module.angle_rad, toward_center), angle_error(module.angle_rad, toward_center + math.pi)
            ) < math.radians(1)
            assert module.setpoint.speed_mps == 0.0
        driver.teleop.initialize()
        driver.forward = 1.0
        driver.run(1.0)
        assert driver.drive.pose.X() > 1.0


def test_unknown_alliance_counts_as_blue():
    from utils.alliance import is_red_alliance

    assert is_red_alliance() is False


@pytest.mark.parametrize(
    "module_name",
    [
        "commands.drive.stick_shaping",
        "commands.drive.heading_lock",
        "commands.drive.teleop_drive",
        "commands.drive.x_lock",
        "utils.alliance",
    ],
)
def test_docstring_examples(module_name):
    """The examples in the docstrings are run here so they stay correct."""
    result = doctest.testmod(importlib.import_module(module_name), optionflags=doctest.ELLIPSIS)
    assert result.attempted > 0
    assert result.failed == 0
