"""Unit tests for __str__ on managed inputs and ShapingPipeline.
# Generated by Claude

Verifies that __str__ output on ManagedButton, ManagedAnalog,
ManagedRumble, and ShapingPipeline includes the expected details
(action name, binding info, pipeline description, etc.).

Also includes a factory-level test that creates all controls from the
test YAML and prints them — useful as a quick visual sanity check.
"""

import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from utils.controller.model import (
    ActionDefinition,
    EventTriggerMode,
    InputType,
)
from utils.input.managed_analog import ManagedAnalog
from utils.input.managed_button import ManagedButton
from utils.input.managed_rumble import ManagedRumble
from utils.input.shaping import build_shaping_pipeline, ShapingPipeline
from utils.math.curves import default_spline_points, default_segment_points


# --- Helpers ---

def _make_action(
    name="test_action",
    group="test",
    input_type=InputType.ANALOG,
    trigger_mode=EventTriggerMode.SCALED,
    deadband=0.05,
    scale=1.0,
    inversion=False,
    slew_rate=0.0,
    threshold=0.5,
    extra=None,
):
    return ActionDefinition(
        name=name,
        group=group,
        description="test",
        input_type=input_type,
        trigger_mode=trigger_mode,
        deadband=deadband,
        scale=scale,
        inversion=inversion,
        slew_rate=slew_rate,
        threshold=threshold,
        extra=extra or {},
    )


# --- ShapingPipeline __str__ ---

class TestShapingPipelineStr:

    def test_raw_passthrough(self):
        p = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.RAW, scale=1.0, extra={})
        assert isinstance(p, ShapingPipeline)
        assert str(p) == "raw passthrough"

    def test_scaled_no_transforms(self):
        p = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SCALED, scale=1.0, extra={})
        assert str(p) == "scaled"

    def test_scaled_with_all_stages(self):
        p = build_shaping_pipeline(
            inversion=True, deadband=0.1,
            trigger_mode=EventTriggerMode.SCALED, scale=2.0, extra={})
        s = str(p)
        assert "invert" in s
        assert "deadband(0.1)" in s
        assert "scale(2.0)" in s

    def test_squared_mode(self):
        p = build_shaping_pipeline(
            inversion=False, deadband=0.05,
            trigger_mode=EventTriggerMode.SQUARED, scale=1.0, extra={})
        s = str(p)
        assert "deadband(0.05)" in s
        assert "squared" in s

    def test_spline_mode(self):
        pts = default_spline_points()
        p = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SPLINE, scale=1.0,
            extra={"spline_points": pts})
        s = str(p)
        assert "spline(" in s
        assert "pts)" in s

    def test_segmented_mode(self):
        pts = default_segment_points()
        p = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SEGMENTED, scale=1.0,
            extra={"segment_points": pts})
        s = str(p)
        assert "segments(" in s
        assert "pts)" in s

    def test_callable(self):
        """ShapingPipeline should still work as a callable."""
        p = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SCALED, scale=2.0, extra={})
        assert p(0.5) == 1.0


# --- ManagedAnalog __str__ ---

class TestManagedAnalogStr:

    def test_basic_str(self):
        action = _make_action(trigger_mode=EventTriggerMode.SCALED,
                              deadband=0.1, scale=2.0)
        analog = ManagedAnalog(action, lambda: 0.0)
        s = str(analog)
        assert "ManagedAnalog(" in s
        assert "test.test_action" in s
        assert "mode=scaled" in s
        assert "pipeline=" in s
        assert "bind=" in s

    def test_binding_info_default_unbound(self):
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        assert "bind=unbound" in str(analog)

    def test_binding_info_set(self):
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        analog._binding_info = "Driver.left_stick_x (0)"
        s = str(analog)
        assert "bind=Driver.left_stick_x (0)" in s

    def test_slew_rate_shown(self):
        action = _make_action(slew_rate=3.0)
        analog = ManagedAnalog(action, lambda: 0.0)
        s = str(analog)
        assert "slew_rate=3.0" in s

    def test_no_slew_rate_when_zero(self):
        action = _make_action(slew_rate=0.0)
        analog = ManagedAnalog(action, lambda: 0.0)
        assert "slew_rate" not in str(analog)

    def test_no_action(self):
        analog = ManagedAnalog(None, lambda: 0.0)
        s = str(analog)
        assert "unbound" in s


# --- ManagedButton __str__ ---

class TestManagedButtonStr:

    def test_basic_str(self):
        action = _make_action(input_type=InputType.BUTTON,
                              trigger_mode=EventTriggerMode.ON_TRUE)
        btn = ManagedButton(action, lambda: False)
        s = str(btn)
        assert "ManagedButton(" in s
        assert "test.test_action" in s
        assert "type=button" in s
        assert "mode=on_true" in s

    def test_binding_info_default_unbound(self):
        action = _make_action(input_type=InputType.BUTTON)
        btn = ManagedButton(action, lambda: False)
        assert "bind=unbound" in str(btn)

    def test_binding_info_set(self):
        action = _make_action(input_type=InputType.BUTTON)
        btn = ManagedButton(action, lambda: False)
        btn._binding_info = "Operator.y_button (4)"
        assert "bind=Operator.y_button (4)" in str(btn)

    def test_boolean_trigger_shows_threshold(self):
        action = _make_action(input_type=InputType.BOOLEAN_TRIGGER,
                              trigger_mode=EventTriggerMode.TOGGLE_ON_TRUE,
                              threshold=0.75)
        btn = ManagedButton(action, lambda: False)
        s = str(btn)
        assert "type=boolean_trigger" in s
        assert "threshold=0.75" in s

    def test_regular_button_no_threshold(self):
        action = _make_action(input_type=InputType.BUTTON)
        btn = ManagedButton(action, lambda: False)
        assert "threshold" not in str(btn)

    def test_no_action(self):
        btn = ManagedButton(None, lambda: False)
        s = str(btn)
        assert "unbound" in s


# --- ManagedRumble __str__ ---

class TestManagedRumbleStr:

    def test_basic_str(self):
        action = _make_action(input_type=InputType.OUTPUT,
                              trigger_mode=EventTriggerMode.RAW)
        rumble = ManagedRumble(action, lambda v: None)
        s = str(rumble)
        assert "ManagedRumble(" in s
        assert "test.test_action" in s

    def test_binding_info_set(self):
        action = _make_action(input_type=InputType.OUTPUT)
        rumble = ManagedRumble(action, lambda v: None)
        rumble._binding_info = "Driver.rumble_left (0)"
        assert "bind=Driver.rumble_left (0)" in str(rumble)

    def test_no_action(self):
        rumble = ManagedRumble(None, lambda v: None)
        assert "unbound" in str(rumble)


# --- Factory-level: print all controls from test YAML ---

class TestFactoryPrintAllControls:
    """Create all controls from the test YAML and print their __str__.

    This test uses the InputFactory with the test config to verify
    that every managed object can be printed without error and
    contains the expected binding info.
    """

    def test_print_all_controls(self):
        from utils.input.factory import InputFactory

        yaml_path = os.path.join(
            os.path.dirname(__file__), "..",
            "data", "inputs", "general_unit_test_mappings.yaml")

        factory = InputFactory(
            config_path=yaml_path, register_global=False)

        printed = []

        # Buttons
        for qn, action in factory.config.actions.items():
            if action.input_type in (
                InputType.BUTTON, InputType.BOOLEAN_TRIGGER
            ):
                btn = factory.getButton(qn, required=False)
                s = str(btn)
                printed.append(s)
                assert qn in s
                # Bound buttons should show controller info
                if btn._binding_info != "unbound":
                    assert "Driver." in s or "Operator." in s

        # Analogs (including virtual)
        for qn, action in factory.config.actions.items():
            if action.input_type in (
                InputType.ANALOG, InputType.VIRTUAL_ANALOG
            ):
                analog = factory.getAnalog(qn, required=False)
                s = str(analog)
                printed.append(s)
                assert qn in s
                assert "pipeline=" in s
                if analog._binding_info != "unbound":
                    assert "Driver." in s or "Operator." in s

        # Rumbles
        for qn, action in factory.config.actions.items():
            if action.input_type == InputType.OUTPUT:
                rumble = factory.getRumbleControl(qn, required=False)
                s = str(rumble)
                printed.append(s)
                assert qn in s
                if rumble._binding_info != "unbound":
                    assert "Driver." in s or "Operator." in s

        # Print all for visual inspection (visible with pytest -s)
        print("\n--- All managed inputs ---")
        for line in printed:
            print(f"  {line}")
        print(f"--- Total: {len(printed)} ---")

        assert len(printed) > 0
