"""Tests for utils.loop_timing.LoopTimer NT publishing.
# Generated by Claude
"""

import ntcore
import wpilib.simulation

from utils.loop_timing import LoopTimer


def _last_ms_entry():
    table = ntcore.NetworkTableInstance.getDefault().getTable("FrameTiming")
    return table.getSubTable("userCode").getEntry("lastMs")


class TestLoopTimerPublish:
    def setup_method(self):
        wpilib.simulation.pauseTiming()
        wpilib.simulation.restartTiming()

    def teardown_method(self):
        wpilib.simulation.resumeTiming()

    def _cycle(self, timer, work_sec):
        timer.start("userCode")
        wpilib.simulation.stepTiming(work_sec)
        timer.stop("userCode")
        timer.publish()

    def test_publishes_under_frame_timing(self):
        timer = LoopTimer(budget_sec=0.020)
        timer.add_channel("userCode")
        self._cycle(timer, 0.005)
        assert abs(_last_ms_entry().getDouble(-1.0) - 5.0) < 0.5

    def test_throttles_nt_writes_to_publish_period(self):
        timer = LoopTimer(budget_sec=0.020, publish_period_sec=0.1)
        timer.add_channel("userCode")
        self._cycle(timer, 0.005)  # first call publishes
        first = _last_ms_entry().getDouble(-1.0)

        # 20 ms later is inside the 100 ms window: no new NT write
        self._cycle(timer, 0.010)
        assert _last_ms_entry().getDouble(-1.0) == first

        # Past the window: the latest value is published
        wpilib.simulation.stepTiming(0.1)
        self._cycle(timer, 0.010)
        assert abs(_last_ms_entry().getDouble(-1.0) - 10.0) < 0.5
