"""
Drive the whole simulated robot with a simulated Xbox controller.

Generated by Claude. This boots ``robot.py`` like ``robotpy sim`` does, pushes
the sticks and buttons through WPILib's controller sim, and checks the robot
goes where the driver expects on both alliances. It covers the parts the
tests in tests/drivetrain/test_teleop.py skip: the YAML bindings, stick
directions and InputFactory.
"""

import math

import hal
import pytest
import wpilib.simulation
from wpilib.simulation import DriverStationSim, XboxControllerSim

from robot import MyRobot

_STEP_PERIOD = (MyRobot.kDefaultPeriod / 1000) - 0.001


def step(seconds):
    for _ in range(round(seconds / 0.02)):
        DriverStationSim.notifyNewData()
        wpilib.simulation.stepTiming(_STEP_PERIOD)


def start_teleop(control, red):
    control.step_timing(seconds=0.5, autonomous=False, enabled=False)
    station = hal.AllianceStationID.kRed1 if red else hal.AllianceStationID.kBlue1
    DriverStationSim.setAllianceStationId(station)
    DriverStationSim.setAutonomous(False)
    DriverStationSim.setEnabled(True)
    step(0.1)


def press(stick, setter, seconds=0.1):
    setter(True)
    stick.notifyNewData()
    step(seconds)
    setter(False)
    stick.notifyNewData()
    step(0.04)


@pytest.mark.parametrize("red", [False, True], ids=["blue", "red"])
def test_left_stick_forward_drives_away_from_the_driver(control, robot, red):
    stick = XboxControllerSim(0)
    with control.run_robot():
        start_teleop(control, red)
        press(stick, stick.setStartButton)  # re-zero: robot faces away from the driver
        start_x = robot.drivetrain.pose.X()

        stick.setLeftY(-1.0)  # stick pushed up reads -1
        stick.notifyNewData()
        step(1.0)
        moved = robot.drivetrain.pose.X() - start_x
        assert (moved < -1.0) if red else (moved > 1.0)
        assert robot.drive_sim.true_pose.x_m > 1.0  # toward the robot's own front

        stick.setLeftY(0.0)
        stick.setLeftX(-1.0)  # stick pushed left reads -1
        stick.notifyNewData()
        start_y = robot.drivetrain.pose.Y()
        step(1.5)
        moved = robot.drivetrain.pose.Y() - start_y
        assert (moved < -1.0) if red else (moved > 1.0)


def test_right_stick_right_turns_clockwise(control, robot):
    stick = XboxControllerSim(0)
    with control.run_robot():
        start_teleop(control, red=False)
        stick.setRightX(1.0)
        stick.notifyNewData()
        step(0.3)
        assert robot.drivetrain.measured_speeds.omega_rad_per_s < -1.0


def test_x_button_holds_the_wheels_in_an_x(control, robot):
    stick = XboxControllerSim(0)
    with control.run_robot():
        start_teleop(control, red=False)
        stick.setXButton(True)
        stick.notifyNewData()
        step(0.5)
        for module, corner in zip(robot.drivetrain.modules, robot.robot_config.corners):
            toward_center = math.atan2(corner.y_m, corner.x_m)
            error = abs(math.remainder(module.angle_rad - toward_center, math.pi))
            assert error < math.radians(2)
        stick.setXButton(False)
        stick.setLeftY(-1.0)
        stick.notifyNewData()
        step(1.0)
        assert robot.drivetrain.pose.X() > 1.0  # teleop took over again
