"""Unit tests for config validation — runs during deploy.
# Generated by Claude

Validates controller config YAML files load correctly and pass
structural validation.  These tests run automatically during
``python -m robotpy test`` to catch malformed configs before
they reach the robot.
"""

import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from utils.controller.config_io import load_config
from utils.input.validation import validate_config


# Paths to config files
_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "inputs")
_UNIT_TEST_YAML = os.path.join(_DATA_DIR, "general_unit_test_mappings.yaml")
_CONTROLLER_YAML = os.path.join(_DATA_DIR, "controller.yaml")


class TestUnitTestMappingsConfig:
    """Validate data/general_unit_test_mappings.yaml."""

    def test_loads_without_error(self):
        config = load_config(_UNIT_TEST_YAML)
        assert config is not None

    def test_has_actions(self):
        config = load_config(_UNIT_TEST_YAML)
        assert len(config.actions) > 0

    def test_has_controllers(self):
        config = load_config(_UNIT_TEST_YAML)
        assert len(config.controllers) > 0

    def test_all_bindings_reference_existing_actions(self):
        config = load_config(_UNIT_TEST_YAML)
        for port, ctrl in config.controllers.items():
            for input_name, action_names in ctrl.bindings.items():
                for action_name in action_names:
                    assert action_name in config.actions, (
                        f"Controller {port} input '{input_name}' "
                        f"references unknown action '{action_name}'")

    def test_validation_no_errors(self):
        """Config should pass validation with no errors (warnings OK)."""
        config = load_config(_UNIT_TEST_YAML)
        issues = validate_config(config)
        errors = [i for i in issues if i.level == "error"]
        if errors:
            msg = "\n".join(str(e) for e in errors)
            assert False, f"Validation errors:\n{msg}"

    def test_action_groups_loaded(self):
        """Should have actions in both 'general' and 'test_group'."""
        config = load_config(_UNIT_TEST_YAML)
        groups = {a.group for a in config.actions.values()}
        assert "general" in groups
        assert "test_group" in groups

    def test_spline_action_has_points(self):
        """Spline action should have spline_points in extra."""
        config = load_config(_UNIT_TEST_YAML)
        spline_action = config.actions.get("general.general_analog_spline")
        assert spline_action is not None
        assert "spline_points" in spline_action.extra
        pts = spline_action.extra["spline_points"]
        assert len(pts) >= 2

    def test_segmented_action_has_points(self):
        """Segmented action should have segment_points in extra."""
        config = load_config(_UNIT_TEST_YAML)
        seg_action = config.actions.get("general.general_analog_point")
        assert seg_action is not None
        assert "segment_points" in seg_action.extra
        pts = seg_action.extra["segment_points"]
        assert len(pts) >= 2

    def test_output_actions_exist(self):
        """Rumble output actions should load correctly."""
        config = load_config(_UNIT_TEST_YAML)
        from utils.controller.model import InputType
        output_actions = [
            a for a in config.actions.values()
            if a.input_type == InputType.OUTPUT
        ]
        assert len(output_actions) >= 3

    def test_trigger_modes_loaded(self):
        """Various trigger modes should load correctly."""
        config = load_config(_UNIT_TEST_YAML)
        from utils.controller.model import EventTriggerMode
        modes_found = {a.trigger_mode for a in config.actions.values()}
        assert EventTriggerMode.ON_TRUE in modes_found
        assert EventTriggerMode.ON_FALSE in modes_found
        assert EventTriggerMode.WHILE_TRUE in modes_found
        assert EventTriggerMode.WHILE_FALSE in modes_found
        assert EventTriggerMode.TOGGLE_ON_TRUE in modes_found

    def test_analog_properties_loaded(self):
        """Analog actions should have correct properties from YAML."""
        config = load_config(_UNIT_TEST_YAML)
        scaled = config.actions.get(
            "general.general_analog_scaled_deadzone")
        assert scaled is not None
        assert scaled.deadband == 0.1
        assert scaled.scale == 12.0

    def test_inversion_loaded(self):
        """Inverted action should have inversion=True."""
        config = load_config(_UNIT_TEST_YAML)
        inverted = config.actions.get(
            "general.general_analog_raw_inverted")
        assert inverted is not None
        assert inverted.inversion is True

    # Generated by Claude
    def test_boolean_trigger_loaded(self):
        """BOOLEAN_TRIGGER action should load with correct type and threshold."""
        config = load_config(_UNIT_TEST_YAML)
        from utils.controller.model import InputType, EventTriggerMode
        action = config.actions.get("general.general_bool_trigger")
        assert action is not None
        assert action.input_type == InputType.BOOLEAN_TRIGGER
        assert action.trigger_mode == EventTriggerMode.TOGGLE_ON_TRUE
        assert action.threshold == 0.5

    # Generated by Claude
    def test_boolean_trigger_validation(self):
        """BOOLEAN_TRIGGER bound to axis should pass validation."""
        config = load_config(_UNIT_TEST_YAML)
        issues = validate_config(config)
        errors = [i for i in issues if i.level == "error"]
        # No errors from the boolean_trigger binding to right_trigger
        bt_errors = [e for e in errors if "bool_trigger" in str(e)]
        assert bt_errors == [], f"Boolean trigger errors: {bt_errors}"


    # Generated by Claude
    def test_virtual_analog_loaded(self):
        """VIRTUAL_ANALOG action should load with correct type."""
        config = load_config(_UNIT_TEST_YAML)
        from utils.controller.model import InputType
        action = config.actions.get("general.general_virtual_speed")
        assert action is not None
        assert action.input_type == InputType.VIRTUAL_ANALOG
        assert action.extra.get("va_ramp_rate") == 2.0
        assert action.extra.get("va_acceleration") == 5.0

    # Generated by Claude
    def test_virtual_analog_validation(self):
        """VIRTUAL_ANALOG bound to button should pass validation."""
        config = load_config(_UNIT_TEST_YAML)
        issues = validate_config(config)
        errors = [i for i in issues if i.level == "error"]
        va_errors = [e for e in errors if "virtual_speed" in str(e)]
        assert va_errors == [], f"Virtual analog errors: {va_errors}"

    # Generated by Claude
    def test_config_version_loaded(self):
        """Config should load with version field."""
        config = load_config(_UNIT_TEST_YAML)
        assert config.version == "1.0.0"


class TestControllerYamlConfig:
    """Validate data/controller.yaml (real robot config)."""

    def test_loads_without_error(self):
        if not os.path.exists(_CONTROLLER_YAML):
            return  # Skip if not present
        config = load_config(_CONTROLLER_YAML)
        assert config is not None

    def test_validation_no_errors(self):
        if not os.path.exists(_CONTROLLER_YAML):
            return
        config = load_config(_CONTROLLER_YAML)
        issues = validate_config(config)
        errors = [i for i in issues if i.level == "error"]
        if errors:
            msg = "\n".join(str(e) for e in errors)
            assert False, f"Validation errors:\n{msg}"

    def test_all_bindings_reference_existing_actions(self):
        if not os.path.exists(_CONTROLLER_YAML):
            return
        config = load_config(_CONTROLLER_YAML)
        for port, ctrl in config.controllers.items():
            for input_name, action_names in ctrl.bindings.items():
                for action_name in action_names:
                    assert action_name in config.actions, (
                        f"Controller {port} input '{input_name}' "
                        f"references unknown action '{action_name}'")
