"""
Test mode on the whole simulated robot: pick a test, hold A to run it, let go to stop.

Generated by Claude. This boots ``robot.py`` like ``robotpy sim`` does, picks
an option on the Characterization chooser (through NetworkTables, like the
dashboard, or with the controller), enables test mode and holds the run
button with WPILib's controller sim.
"""

import math

import ntcore
import pytest
import wpilib.simulation
from wpilib.simulation import DriverStationSim, XboxControllerSim

from robot import MyRobot

_STEP_PERIOD = (MyRobot.kDefaultPeriod / 1000) - 0.001

pytestmark = pytest.mark.skipif(
    not hasattr(DriverStationSim, "setTest"), reason="RobotPy 2027 replaces test mode with op modes"
)


def step(seconds):
    for _ in range(round(seconds / 0.02)):
        DriverStationSim.notifyNewData()
        wpilib.simulation.stepTiming(_STEP_PERIOD)


def pick_on_dashboard(option):
    """Pick an option on the dashboard's Characterization chooser, like a driver would."""
    topic = ntcore.NetworkTableInstance.getDefault().getStringTopic("/SmartDashboard/Characterization/selected")
    publisher = topic.publish()
    publisher.set(option)
    return publisher


def enable_test_mode(control):
    control.step_timing(seconds=0.5, autonomous=False, enabled=False)
    DriverStationSim.setAutonomous(False)
    DriverStationSim.setTest(True)
    DriverStationSim.setEnabled(True)
    step(0.1)


def hold_a(stick, held):
    stick.setAButton(held)
    stick.notifyNewData()


def press(stick, setter):
    setter(True)
    stick.notifyNewData()
    step(0.1)
    setter(False)
    stick.notifyNewData()
    step(0.1)


def test_nothing_runs_until_a_is_held(control, robot):
    stick = XboxControllerSim(0)
    publisher = pick_on_dashboard("Module check")
    with control.run_robot():
        enable_test_mode(control)
        step(1.0)
        assert robot.characterization.running is None
        hold_a(stick, True)
        step(1.0)
        assert robot.characterization.running is robot.characterization.selected()  # module check
        for module in robot.drivetrain.modules:
            assert abs(math.remainder(module.angle_rad, math.tau)) < math.radians(2)
        step(3.0)  # second step of the module check: 90 degrees
        for module in robot.drivetrain.modules:
            assert abs(math.remainder(module.angle_rad - math.pi / 2, math.tau)) < math.radians(2)
    publisher.close()


def test_letting_go_of_a_stops_the_test(control, robot):
    stick = XboxControllerSim(0)
    publisher = pick_on_dashboard("Wheel radius")
    with control.run_robot():
        enable_test_mode(control)
        hold_a(stick, True)
        step(3.0)
        assert robot.drivetrain.measured_speeds.omega_rad_per_s > 0.5  # spinning in place
        hold_a(stick, False)
        step(0.5)
        assert robot.characterization.running is None
        assert abs(robot.drivetrain.measured_speeds.omega_rad_per_s) < 0.1
    publisher.close()


def test_drive_sysid_stops_when_a_is_let_go(control, robot):
    stick = XboxControllerSim(0)
    publisher = pick_on_dashboard("SysId drive: dynamic forward")
    with control.run_robot():
        enable_test_mode(control)
        hold_a(stick, True)
        step(1.5)
        assert robot.drivetrain.measured_speeds.vx_mps > 0.5
        hold_a(stick, False)
        step(0.5)
        assert abs(robot.drivetrain.measured_speeds.vx_mps) < 0.1
    publisher.close()


def test_a_does_nothing_outside_test_mode(control, robot):
    stick = XboxControllerSim(0)
    with control.run_robot():
        control.step_timing(seconds=0.5, autonomous=False, enabled=False)
        DriverStationSim.setTest(False)  # teleop
        DriverStationSim.setEnabled(True)
        hold_a(stick, True)
        step(0.5)
        assert robot.characterization.running is None


def test_b_and_left_bumper_step_through_the_tests(control, robot):
    stick = XboxControllerSim(0)
    publisher = pick_on_dashboard("Module check")
    with control.run_robot():
        enable_test_mode(control)
        names = robot.characterization.names
        assert robot.characterization.selected_name == names[0]
        press(stick, stick.setBButton)
        assert robot.characterization.selected_name == names[1]
        press(stick, stick.setLeftBumperButton)
        press(stick, stick.setLeftBumperButton)
        assert robot.characterization.selected_name == names[-1]  # wraps around
    publisher.close()
