"""
Unit tests for utils/geometry.py transform builders and geometry classes.

Tests validate:
- inches_to_meters conversion
- transform_from_inches builds correct Transform3d
- Pitch sign convention (positive pitch_up_deg → negative WPI pitch)
- Yaw convention (90° = left)
- chain_transforms composes correctly
- chain_transforms with identity
- CameraGeometry.to_dict roundtrips correctly
- MechanismMount with parent chaining
- MechanismMount.to_dict extracts correct yaw

Generated by Claude.
"""

from wpimath.geometry import Transform3d, Translation3d

from utils.geometry import (
    MechanismMount,
    chain_transforms,
    inches_to_meters,
    make_camera,
    transform_from_inches,
)


class TestInchesToMeters:
    def test_one_inch(self):
        assert abs(inches_to_meters(1.0) - 0.0254) < 1e-9

    def test_zero(self):
        assert inches_to_meters(0) == 0

    def test_negative(self):
        assert abs(inches_to_meters(-10) - (-0.254)) < 1e-9

    def test_large(self):
        # 100 inches = 2.54 meters
        assert abs(inches_to_meters(100) - 2.54) < 1e-9


class TestTransformFromInches:
    def test_translation_only(self):
        tf = transform_from_inches(x_in=10, y_in=5, z_in=12)
        t = tf.translation()
        assert abs(t.X() - 0.254) < 1e-6
        assert abs(t.Y() - 0.127) < 1e-6
        assert abs(t.Z() - 0.3048) < 1e-6

    def test_zero_transform(self):
        tf = transform_from_inches()
        t = tf.translation()
        assert abs(t.X()) < 1e-9
        assert abs(t.Y()) < 1e-9
        assert abs(t.Z()) < 1e-9

    def test_pitch_sign_convention(self):
        """Positive pitch_up_deg should produce negative WPI pitch."""
        tf = transform_from_inches(pitch_up_deg=15)
        r = tf.rotation()
        # WPI pitch is the Y rotation; positive pitch_up → negative WPI pitch
        # Check that rotating a forward vector tilts it upward (+Z)
        forward = Translation3d(1, 0, 0)
        rotated = forward.rotateBy(r)
        # With 15° up pitch, Z component should be positive
        assert rotated.Z() > 0, f"Expected positive Z, got {rotated.Z()}"

    def test_yaw_90_points_left(self):
        """Yaw 90° should point along +Y (left in WPI)."""
        tf = transform_from_inches(yaw_deg=90)
        r = tf.rotation()
        forward = Translation3d(1, 0, 0)
        rotated = forward.rotateBy(r)
        # Should be pointing along +Y
        assert abs(rotated.X()) < 0.01
        assert rotated.Y() > 0.9

    def test_yaw_180_points_backward(self):
        """Yaw 180° should point along -X (backward)."""
        tf = transform_from_inches(yaw_deg=180)
        r = tf.rotation()
        forward = Translation3d(1, 0, 0)
        rotated = forward.rotateBy(r)
        assert rotated.X() < -0.9
        assert abs(rotated.Y()) < 0.01


class TestChainTransforms:
    def test_identity_chain(self):
        """Chaining with identity should not change the transform."""
        tf = transform_from_inches(x_in=5, z_in=10)
        identity = Transform3d()
        chained = chain_transforms(tf, identity)
        t = chained.translation()
        assert abs(t.X() - tf.translation().X()) < 1e-9
        assert abs(t.Z() - tf.translation().Z()) < 1e-9

    def test_translation_chain(self):
        """Two translations should add."""
        a = transform_from_inches(x_in=10)
        b = transform_from_inches(x_in=5)
        chained = chain_transforms(a, b)
        t = chained.translation()
        expected = inches_to_meters(15)
        assert abs(t.X() - expected) < 1e-9

    def test_turret_hood_chain(self):
        """Turret at (-2, 0, 6) + hood at (0, 0, 2) relative to turret
        should give hood at (-2, 0, 8) from robot center."""
        robot_to_turret = transform_from_inches(x_in=-2, z_in=6)
        turret_to_hood = transform_from_inches(z_in=2)
        chained = chain_transforms(robot_to_turret, turret_to_hood)
        t = chained.translation()
        assert abs(t.X() - inches_to_meters(-2)) < 1e-6
        assert abs(t.Y()) < 1e-9
        assert abs(t.Z() - inches_to_meters(8)) < 1e-6

    def test_rotation_chain(self):
        """Chaining two 90° yaw rotations should give 180°."""
        a = transform_from_inches(yaw_deg=90)
        b = transform_from_inches(yaw_deg=90)
        chained = chain_transforms(a, b)
        r = chained.rotation()
        forward = Translation3d(1, 0, 0)
        rotated = forward.rotateBy(r)
        # 180° yaw → pointing -X
        assert rotated.X() < -0.9

    def test_single_transform(self):
        """Chain of one should equal the original."""
        tf = transform_from_inches(x_in=3, y_in=4, z_in=5, yaw_deg=45)
        chained = chain_transforms(tf)
        t1 = tf.translation()
        t2 = chained.translation()
        assert abs(t1.X() - t2.X()) < 1e-9
        assert abs(t1.Y() - t2.Y()) < 1e-9
        assert abs(t1.Z() - t2.Z()) < 1e-9


class TestCameraGeometry:
    def test_make_camera_to_dict_roundtrip(self):
        cam = make_camera(
            "Test_Cam", x_in=6, y_in=-3, z_in=12,
            pitch_up_deg=15, yaw_deg=90, fov_deg=70,
        )
        d = cam.to_dict()
        assert d["name"] == "Test_Cam"
        assert abs(d["x_inches"] - 6) < 1e-9
        assert abs(d["y_inches"] - (-3)) < 1e-9
        assert abs(d["z_inches"] - 12) < 1e-9
        assert abs(d["pitch_deg"] - 15) < 1e-9
        assert abs(d["yaw_deg"] - 90) < 1e-9
        assert abs(d["fov_deg"] - 70) < 1e-9
        # WPI rotation: pitch is negated
        assert abs(d["wpi_rotation_deg"]["pitch"] - (-15)) < 1e-9

    def test_camera_transform3d(self):
        cam = make_camera("Cam", x_in=10, z_in=12, yaw_deg=180)
        tf = cam.robot_to_camera
        t = tf.translation()
        assert abs(t.X() - inches_to_meters(10)) < 1e-6
        assert abs(t.Z() - inches_to_meters(12)) < 1e-6

    def test_camera_meters_in_dict(self):
        cam = make_camera("Cam", x_in=10, y_in=5, z_in=12)
        d = cam.to_dict()
        assert abs(d["x_meters"] - 0.254) < 0.001
        assert abs(d["y_meters"] - 0.127) < 0.001
        assert abs(d["z_meters"] - 0.3048) < 0.001


class TestMechanismMount:
    def test_simple_mechanism(self):
        mech = MechanismMount(
            "Turret", "turret",
            transform_from_inches(x_in=-2, z_in=6),
            radius_in=4, color="#cc5555",
        )
        d = mech.to_dict()
        assert d["name"] == "Turret"
        assert d["type"] == "turret"
        assert abs(d["x_inches"] - (-2)) < 0.1
        assert abs(d["z_inches"] - 6) < 0.1
        assert abs(d["radius_inches"] - 4) < 0.1

    def test_chained_mechanism(self):
        """Hood relative to turret should resolve to absolute position."""
        robot_to_turret = transform_from_inches(x_in=-2, z_in=6)
        turret_to_hood = transform_from_inches(z_in=2)
        hood = MechanismMount(
            "Hood", "generic", turret_to_hood,
            parent_transform=robot_to_turret, parent_name="Turret",
            width_in=3, length_in=2,
        )
        d = hood.to_dict()
        assert d["parent"] == "Turret"
        # Hood should be at turret pos + (0, 0, 2")
        assert abs(d["z_inches"] - 8) < 0.1
        assert abs(d["x_inches"] - (-2)) < 0.1

    def test_mechanism_to_dict_meters(self):
        mech = MechanismMount(
            "Test", "generic",
            transform_from_inches(x_in=10, y_in=5, z_in=12),
        )
        d = mech.to_dict()
        assert abs(d["x_meters"] - 0.254) < 0.001
        assert abs(d["y_meters"] - 0.127) < 0.001
        assert abs(d["z_meters"] - 0.3048) < 0.001


class TestRobotGeometryIntegration:
    """Test that the actual robot geometry values load correctly."""

    def test_swerve_positions_symmetric(self):
        from constants.robot_geometry import (
            SWERVE_FL, SWERVE_FR, SWERVE_BL,
        )
        # FL and FR should be symmetric about Y
        assert abs(SWERVE_FL.X() - SWERVE_FR.X()) < 1e-9
        assert abs(SWERVE_FL.Y() + SWERVE_FR.Y()) < 1e-9
        # FL and BL should be symmetric about X
        assert abs(SWERVE_FL.X() + SWERVE_BL.X()) < 1e-9
        assert abs(SWERVE_FL.Y() - SWERVE_BL.Y()) < 1e-9

    def test_cameras_load(self):
        from constants.robot_geometry import CAMERAS
        assert len(CAMERAS) >= 2
        names = [c.name for c in CAMERAS]
        assert "Side_Camera" in names
        assert "Back_Camera" in names

    def test_mechanisms_load(self):
        from constants.robot_geometry import MECHANISMS
        assert len(MECHANISMS) >= 5  # 4 swerve + turret + hood
        types = [m.type for m in MECHANISMS]
        assert "swerve_module" in types
        assert "turret" in types

    def test_camera_to_dict_all_fields(self):
        from constants.robot_geometry import CAMERAS
        for cam in CAMERAS:
            d = cam.to_dict()
            required = [
                "name", "x_inches", "y_inches", "z_inches",
                "roll_deg", "pitch_deg", "yaw_deg", "fov_deg",
                "x_meters", "y_meters", "z_meters", "wpi_rotation_deg",
            ]
            for key in required:
                assert key in d, f"Missing key '{key}' in {cam.name}"

    def test_mechanism_to_dict_all_fields(self):
        from constants.robot_geometry import MECHANISMS
        for mech in MECHANISMS:
            d = mech.to_dict()
            required = [
                "name", "type", "x_inches", "y_inches", "z_inches",
                "yaw_deg", "x_meters", "y_meters", "z_meters",
            ]
            for key in required:
                assert key in d, f"Missing key '{key}' in {mech.name}"
