"""Unit tests for custom NT parameter mapping on managed inputs.
# Generated by Claude

Tests mapParamToNtPath, unmap, and clearMaps functionality on
ManagedAnalog and ManagedButton.
"""

import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import ntcore
import pytest

from utils.controller.model import (
    ActionDefinition,
    EventTriggerMode,
    InputType,
)
from utils.input.managed_analog import ManagedAnalog
from utils.input.managed_button import ManagedButton


def _make_action(
    name="test_action",
    group="test",
    input_type=InputType.ANALOG,
    trigger_mode=EventTriggerMode.SCALED,
    deadband=0.05,
    scale=1.0,
    inversion=False,
    slew_rate=0.0,
    threshold=0.5,
):
    """Create a minimal ActionDefinition for testing."""
    return ActionDefinition(
        name=name,
        group=group,
        description="test",
        input_type=input_type,
        trigger_mode=trigger_mode,
        deadband=deadband,
        scale=scale,
        inversion=inversion,
        slew_rate=slew_rate,
        threshold=threshold,
        extra={},
    )


# --- ManagedAnalog param validation ---

class TestAnalogParamValidation:

    def test_valid_params_list(self):
        """All expected params are in the valid set."""
        assert "deadband" in ManagedAnalog._PARAM_TYPES
        assert "inversion" in ManagedAnalog._PARAM_TYPES
        assert "scale" in ManagedAnalog._PARAM_TYPES
        assert "slew_rate" in ManagedAnalog._PARAM_TYPES

    def test_invalid_param_returns_false(self):
        """mapParamToNtPath rejects unknown param names."""
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        result = analog.mapParamToNtPath("/test/path", "not_a_real_param")
        assert result is False

    def test_mapped_params_empty_initially(self):
        """No custom mappings on a fresh ManagedAnalog."""
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        assert len(analog.mapped_params) == 0

    def test_unmap_nonexistent_returns_false(self):
        """Unmapping a param that isn't mapped returns False."""
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        assert analog.unmap("scale") is False

    def test_clear_maps_on_empty(self):
        """clearMaps on empty mapping dict is a no-op."""
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        analog.clearMaps()
        assert len(analog.mapped_params) == 0


# --- ManagedButton param validation ---

class TestButtonParamValidation:

    def test_valid_params_list(self):
        assert "threshold" in ManagedButton._PARAM_TYPES

    def test_invalid_param_returns_false(self):
        action = _make_action(input_type=InputType.BOOLEAN_TRIGGER)
        btn = ManagedButton(action, lambda: False)
        result = btn.mapParamToNtPath("/test/path", "not_a_param")
        assert result is False

    def test_threshold_on_non_boolean_trigger_returns_false(self):
        """Cannot map threshold on a regular button action."""
        action = _make_action(input_type=InputType.BUTTON)
        btn = ManagedButton(action, lambda: False)
        result = btn.mapParamToNtPath("/test/path", "threshold")
        assert result is False

    def test_mapped_params_empty_initially(self):
        action = _make_action(input_type=InputType.BOOLEAN_TRIGGER)
        btn = ManagedButton(action, lambda: False)
        assert len(btn.mapped_params) == 0


# --- NT integration tests (require ntcore) ---

class TestAnalogNtMapping:
    """Integration tests using real ntcore entries."""

    @pytest.fixture(autouse=True)
    def setup_nt(self):
        """Use unique paths per test to avoid NT collisions."""
        self._test_id = id(self)
        yield

    def _nt_path(self, suffix):
        return f"/test_nt_mapping/{self._test_id}/{suffix}"

    def test_map_scale_creates_entry(self):
        action = _make_action(scale=2.0)
        analog = ManagedAnalog(action, lambda: 0.5)
        path = self._nt_path("scale")

        result = analog.mapParamToNtPath(path, "scale")
        assert result is True
        assert "scale" in analog.mapped_params

        # NT entry should exist with current value as default
        entry = ntcore.NetworkTableInstance.getDefault().getEntry(path)
        assert entry.exists()
        assert entry.getDouble(0.0) == 2.0

    def test_map_deadband_creates_entry(self):
        action = _make_action(deadband=0.1)
        analog = ManagedAnalog(action, lambda: 0.0)
        path = self._nt_path("deadband")

        result = analog.mapParamToNtPath(path, "deadband")
        assert result is True
        assert "deadband" in analog.mapped_params

    def test_map_inversion_creates_entry(self):
        action = _make_action(inversion=True)
        analog = ManagedAnalog(action, lambda: 0.0)
        path = self._nt_path("inversion")

        result = analog.mapParamToNtPath(path, "inversion")
        assert result is True
        assert "inversion" in analog.mapped_params

    def test_unmap_removes_mapping(self):
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)
        path = self._nt_path("scale_unmap")

        analog.mapParamToNtPath(path, "scale")
        assert "scale" in analog.mapped_params

        result = analog.unmap("scale")
        assert result is True
        assert "scale" not in analog.mapped_params

    def test_clear_maps_removes_all(self):
        action = _make_action()
        analog = ManagedAnalog(action, lambda: 0.0)

        analog.mapParamToNtPath(self._nt_path("s"), "scale")
        analog.mapParamToNtPath(self._nt_path("d"), "deadband")
        assert len(analog.mapped_params) == 2

        analog.clearMaps()
        assert len(analog.mapped_params) == 0

    def test_remap_same_param_unmaps_first(self):
        """Mapping the same param to a new path replaces the old one."""
        action = _make_action(scale=1.0)
        analog = ManagedAnalog(action, lambda: 0.0)
        path1 = self._nt_path("scale_v1")
        path2 = self._nt_path("scale_v2")

        analog.mapParamToNtPath(path1, "scale")
        analog.mapParamToNtPath(path2, "scale")

        # Should only have one mapping
        assert len(analog.mapped_params) == 1
        assert "scale" in analog.mapped_params

    def test_sync_custom_maps_updates_scale(self):
        """_sync_custom_maps reads NT and updates the property."""
        action = _make_action(scale=1.0)
        analog = ManagedAnalog(action, lambda: 0.5)
        path = self._nt_path("sync_scale")

        analog.mapParamToNtPath(path, "scale")

        # Simulate dashboard changing the value
        entry = ntcore.NetworkTableInstance.getDefault().getEntry(path)
        entry.setDouble(3.5)

        analog._sync_custom_maps()
        assert analog.scale == 3.5

    def test_sync_custom_maps_updates_deadband(self):
        action = _make_action(deadband=0.05)
        analog = ManagedAnalog(action, lambda: 0.0)
        path = self._nt_path("sync_deadband")

        analog.mapParamToNtPath(path, "deadband")

        entry = ntcore.NetworkTableInstance.getDefault().getEntry(path)
        entry.setDouble(0.15)

        analog._sync_custom_maps()
        assert analog.deadband == 0.15

    def test_sync_custom_maps_updates_inversion(self):
        action = _make_action(inversion=False)
        analog = ManagedAnalog(action, lambda: 0.5)
        path = self._nt_path("sync_inv")

        analog.mapParamToNtPath(path, "inversion")

        entry = ntcore.NetworkTableInstance.getDefault().getEntry(path)
        entry.setBoolean(True)

        analog._sync_custom_maps()
        assert analog.inversion is True

    def test_sync_skips_unchanged_value(self):
        """No pipeline rebuild if NT value hasn't changed."""
        action = _make_action(scale=2.0)
        analog = ManagedAnalog(action, lambda: 0.5)
        path = self._nt_path("sync_noop")

        analog.mapParamToNtPath(path, "scale")

        # Don't change the value — sync should be a no-op
        old_pipeline = analog._pipeline
        analog._sync_custom_maps()
        # Pipeline should be the same object (no rebuild)
        assert analog._pipeline is old_pipeline

    def test_map_does_not_overwrite_existing_entry(self):
        """If NT entry already exists, don't overwrite with default."""
        path = self._nt_path("existing_value")
        entry = ntcore.NetworkTableInstance.getDefault().getEntry(path)
        entry.setDouble(7.5)

        action = _make_action(scale=1.0)
        analog = ManagedAnalog(action, lambda: 0.0)

        analog.mapParamToNtPath(path, "scale")

        # Sync should pick up the existing value
        analog._sync_custom_maps()
        assert analog.scale == 7.5


class TestButtonNtMapping:
    """Integration tests for ManagedButton custom NT mapping."""

    @pytest.fixture(autouse=True)
    def setup_nt(self):
        self._test_id = id(self)
        yield

    def _nt_path(self, suffix):
        return f"/test_btn_mapping/{self._test_id}/{suffix}"

    def test_map_threshold_on_boolean_trigger(self):
        action = _make_action(
            input_type=InputType.BOOLEAN_TRIGGER, threshold=0.5)
        btn = ManagedButton(action, lambda: False)
        path = self._nt_path("threshold")

        result = btn.mapParamToNtPath(path, "threshold")
        assert result is True
        assert "threshold" in btn.mapped_params

    def test_unmap_threshold(self):
        action = _make_action(
            input_type=InputType.BOOLEAN_TRIGGER, threshold=0.5)
        btn = ManagedButton(action, lambda: False)
        path = self._nt_path("threshold_unmap")

        btn.mapParamToNtPath(path, "threshold")
        result = btn.unmap("threshold")
        assert result is True
        assert "threshold" not in btn.mapped_params

    def test_clear_maps(self):
        action = _make_action(
            input_type=InputType.BOOLEAN_TRIGGER, threshold=0.5)
        btn = ManagedButton(action, lambda: False)

        btn.mapParamToNtPath(self._nt_path("t"), "threshold")
        assert len(btn.mapped_params) == 1

        btn.clearMaps()
        assert len(btn.mapped_params) == 0
