"""
Tests for the shared SysId tool in utils/sysid/.

Generated by Claude. These use a tiny made-up mechanism (a simulated motor
with known kS, kV and kA) so they check the tool itself; the swerve drive
and steer are tested in tests/drivetrain/test_characterization.py.
"""

import doctest
import importlib
import math

import commands2
import pytest
from wpilib.simulation import DriverStationSim, pauseTiming, resumeTiming, stepTiming

from subsystem.drivetrain.io.sim_motor import SimMotor
from utils.sysid.characterizable import Characterizable, Gravity, Reading
from utils.sysid.chooser import CharacterizationChooser
from utils.sysid.fit import fit_feedforward
from utils.sysid.routines import SysIdTests
from utils.sysid.settings import SysIdSettings


@pytest.fixture
def scheduler():
    """A command scheduler with the robot enabled, and simulated time we step by hand."""
    pauseTiming()
    DriverStationSim.setEnabled(True)
    DriverStationSim.notifyNewData()
    commands2.CommandScheduler.resetInstance()
    yield commands2.CommandScheduler.getInstance()
    commands2.CommandScheduler.getInstance().cancelAll()
    commands2.CommandScheduler.resetInstance()
    DriverStationSim.resetData()
    DriverStationSim.notifyNewData()
    resumeTiming()


def run_until_done(scheduler, command, max_s=60.0):
    """Schedule ``command`` and run 20 ms loops until it finishes. Returns the seconds it took."""
    command.schedule()
    loops = 0
    while scheduler.isScheduled(command) and loops < max_s / 0.02:
        stepTiming(0.02)
        scheduler.run()
        loops += 1
    return loops * 0.02


class FakeMotor(commands2.Subsystem):
    """A motor on its own, simulated with :class:`SimMotor`, that remembers every voltage asked for."""

    def __init__(self, ks=0.3, kv=2.0, ka=0.4):
        super().__init__()
        self.motor = SimMotor(kv=kv, ka=ka, ks=ks)
        self.volts = 0.0
        self.requested: list[float] = []

    def set_voltage(self, volts):
        self.volts = volts
        self.requested.append(volts)

    def periodic(self):
        for _ in range(20):
            self.motor.step(self.volts, 0.001)

    def read(self):
        return Reading(self.volts, self.motor.position, self.motor.velocity)

    def mechanism(self, settings=None, **options):
        return Characterizable(
            name="fake",
            subsystem=self,
            set_voltage=self.set_voltage,
            read=self.read,
            settings=settings or SysIdSettings(timeout_s=4.0, dynamic_timeout_s=1.5),
            **options,
        )


class FakeLift(FakeMotor):
    """A :class:`FakeMotor` that gravity pulls on: an elevator or an arm.

    For an arm the position is in radians with 0 meaning level.
    """

    def __init__(self, gravity, kg=0.8, start_position=0.0, **gains):
        super().__init__(**gains)
        self.gravity = gravity
        self.kg = kg
        self.motor.position = start_position

    def periodic(self):
        for _ in range(20):
            pull = self.kg if self.gravity == Gravity.ELEVATOR else self.kg * math.cos(self.motor.position)
            self.motor.step(self.volts - pull, 0.001)

    def mechanism(self, settings=None, **options):
        return super().mechanism(settings, gravity=self.gravity, **options)


class TestFit:
    def test_recovers_known_numbers(self):
        speed = [1.0 + 0.5 * math.sin(i / 5) for i in range(80)]
        run = [
            Reading(0.3 * math.copysign(1, v) + 2.0 * v + 0.4 * (after - before) / 0.04, 0.0, v)
            for before, v, after in zip(speed, speed[1:], speed[2:])
        ]
        fit = fit_feedforward([run], period_s=0.02)
        assert fit.ks == pytest.approx(0.3, abs=1e-6)
        assert fit.kv == pytest.approx(2.0, abs=1e-6)
        assert fit.ka == pytest.approx(0.4, abs=1e-6)
        assert fit.r_squared == pytest.approx(1.0)

    def test_still_readings_are_left_out(self):
        moving = [Reading(1.0 + i, 0.0, 0.1 * (i + 1) ** 1.5) for i in range(10)]
        still = [Reading(0.0, 0.0, 0.0)] * 5
        # Every moving reading but the last (which has no reading after it) is used.
        assert fit_feedforward([still + moving], 0.02).samples == len(moving) - 1

    def test_too_few_readings_raise(self):
        with pytest.raises(ValueError):
            fit_feedforward([[Reading(1.0, 0.0, 1.0)] * 3], 0.02)

    def test_without_ka_fits_only_ks_and_kv(self):
        run = [Reading(0.3 + 2.0 * v, 0.0, v) for v in (0.1 * i for i in range(1, 30))]
        fit = fit_feedforward([run], 0.02, fit_ka=False)
        assert fit.ks == pytest.approx(0.3)
        assert fit.kv == pytest.approx(2.0)
        assert fit.ka == 0.0

    def test_arm_kg_follows_the_angle(self):
        # An arm sweeping from below level to above it, at changing speeds.
        angles = [-1.0 + 0.04 * i for i in range(60)]
        speeds = [0.5 + 0.3 * math.sin(i / 7) for i in range(60)]
        run = [Reading(0.7 * math.cos(a) + 0.2 + 1.5 * v, a, v) for a, v in zip(angles, speeds)]
        fit = fit_feedforward([run], 0.02, gravity=Gravity.ARM, fit_ka=False)
        assert fit.kg == pytest.approx(0.7)
        assert fit.ks == pytest.approx(0.2)
        assert fit.kv == pytest.approx(1.5)

    def test_a_mechanism_that_never_moved_raises(self):
        with pytest.raises(ValueError):
            fit_feedforward([[Reading(0.5, 0.0, 0.0)] * 50], 0.02)


class TestRoutines:
    def test_all_four_tests_measure_the_motor(self, scheduler):
        fake = FakeMotor(ks=0.3, kv=2.0, ka=0.4)
        tests = SysIdTests(fake.mechanism())
        run_until_done(scheduler, tests.all_tests())
        assert len(tests.runs) == 4
        assert tests.estimate is not None
        assert tests.estimate.ks == pytest.approx(0.3, abs=0.05)
        assert tests.estimate.kv == pytest.approx(2.0, rel=0.03)
        assert tests.estimate.ka == pytest.approx(0.4, rel=0.15)

    def test_quasistatic_ramps_and_reverse_goes_negative(self, scheduler):
        fake = FakeMotor()
        tests = SysIdTests(fake.mechanism(SysIdSettings(ramp_volts_per_s=1.0, timeout_s=2.0)))
        run_until_done(scheduler, tests.quasistatic(forward=False))
        assert min(fake.requested) == pytest.approx(-2.0, abs=0.05)
        assert max(fake.requested) == 0.0
        assert fake.volts == 0.0  # left at 0 V afterward

    def test_dynamic_stops_at_its_own_timeout(self, scheduler):
        fake = FakeMotor()
        tests = SysIdTests(fake.mechanism(SysIdSettings(step_volts=3.0, timeout_s=10.0, dynamic_timeout_s=1.0)))
        run_until_done(scheduler, tests.dynamic())
        assert len(tests.runs[-1]) == pytest.approx(50, abs=2)  # 1 s of 20 ms loops
        assert max(fake.requested) == pytest.approx(3.0)

    def test_never_goes_past_max_volts(self, scheduler):
        fake = FakeMotor()
        settings = SysIdSettings(step_volts=9.0, max_volts=4.0, dynamic_timeout_s=0.5)
        run_until_done(scheduler, SysIdTests(fake.mechanism(settings)).dynamic())
        assert max(abs(v) for v in fake.requested) == pytest.approx(4.0)

    def test_disabling_stops_the_test_at_zero_volts(self, scheduler):
        fake = FakeMotor()
        command = SysIdTests(fake.mechanism()).dynamic()
        command.schedule()
        for _ in range(40):
            stepTiming(0.02)
            scheduler.run()
        assert fake.volts != 0.0
        DriverStationSim.setEnabled(False)
        DriverStationSim.notifyNewData()
        stepTiming(0.02)
        scheduler.run()
        assert not scheduler.isScheduled(command)
        assert fake.volts == 0.0

    def test_writes_no_log_files_in_simulation(self):
        assert SysIdTests(FakeMotor().mechanism()).log_to_wpilog is False


class TestGravityAndLimits:
    def test_elevator_kg(self, scheduler):
        lift = FakeLift(Gravity.ELEVATOR, kg=0.8, ks=0.3, kv=2.0, ka=0.4)
        tests = SysIdTests(lift.mechanism())
        run_until_done(scheduler, tests.all_tests())
        assert tests.estimate is not None
        assert tests.estimate.kg == pytest.approx(0.8, abs=0.05)
        assert tests.estimate.ks == pytest.approx(0.3, abs=0.05)
        assert tests.estimate.kv == pytest.approx(2.0, rel=0.05)

    def test_arm_kg(self, scheduler):
        # Starts hanging down and swings up, stopping before straight up.
        arm = FakeLift(Gravity.ARM, kg=0.8, start_position=-1.5, ks=0.3, kv=2.0, ka=0.4)
        settings = SysIdSettings(ramp_volts_per_s=0.5, step_volts=2.0, timeout_s=8.0, dynamic_timeout_s=1.0)
        tests = SysIdTests(arm.mechanism(settings, min_position=-1.55, max_position=1.2))
        run_until_done(scheduler, tests.quasistatic(forward=True))
        run_until_done(scheduler, tests.dynamic(forward=False))
        assert tests.estimate is not None
        assert tests.estimate.kg == pytest.approx(0.8, abs=0.08)
        assert tests.estimate.kv == pytest.approx(2.0, rel=0.1)

    def test_stops_at_the_position_limit(self, scheduler):
        fake = FakeMotor()
        tests = SysIdTests(fake.mechanism(SysIdSettings(ramp_volts_per_s=2.0, timeout_s=20.0), max_position=1.0))
        seconds = run_until_done(scheduler, tests.quasistatic(forward=True))
        assert seconds < 15.0  # well before the 20 s timeout
        assert 1.0 <= tests.runs[-1][-1].position < 1.1  # the last reading is just past the limit
        assert fake.volts == 0.0

    def test_reverse_limit_does_not_stop_a_forward_test(self, scheduler):
        fake = FakeMotor()
        tests = SysIdTests(fake.mechanism(SysIdSettings(ramp_volts_per_s=2.0, timeout_s=2.0), min_position=0.0))
        run_until_done(scheduler, tests.quasistatic(forward=True))
        assert max(fake.requested) == pytest.approx(4.0, abs=0.05)  # ran to its timeout


class TestChooser:
    def test_default_is_selected(self):
        default = commands2.InstantCommand()
        chooser = CharacterizationChooser("Module check", default)
        assert chooser.selected() is default

    def test_names_must_be_unique(self):
        chooser = CharacterizationChooser("Module check", commands2.InstantCommand())
        with pytest.raises(ValueError):
            chooser.add("Module check", commands2.InstantCommand())

    def test_sysid_adds_five_options(self):
        chooser = CharacterizationChooser("Module check", commands2.InstantCommand())
        chooser.add_sysid(SysIdTests(FakeMotor().mechanism()))
        assert chooser.names[1:] == [
            "SysId fake: all four tests",
            "SysId fake: quasistatic forward",
            "SysId fake: quasistatic reverse",
            "SysId fake: dynamic forward",
            "SysId fake: dynamic reverse",
        ]


@pytest.mark.parametrize(
    "module_name",
    [
        "utils.sysid.settings",
        "utils.sysid.characterizable",
        "utils.sysid.fit",
        "utils.sysid.routines",
        "utils.sysid.chooser",
    ],
)
def test_docstring_examples(module_name):
    result = doctest.testmod(importlib.import_module(module_name), optionflags=doctest.ELLIPSIS)
    assert result.attempted > 0
    assert result.failed == 0
