"""Unit tests for input shaping and curve math.
# Generated by Claude

Tests the portable curve evaluation functions in utils/math/curves
and the shaping pipeline in utils/input/shaping.  Compares spline
and segment output against known values from the test YAML fixture.
"""

import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from utils.math.curves import (
    default_segment_points,
    default_spline_points,
    evaluate_segments,
    evaluate_spline,
    hermite_eval,
    numerical_slope,
)
from utils.input.shaping import (
    apply_deadband,
    build_shaping_pipeline,
    curve_squared,
)
from utils.controller.model import EventTriggerMode


# --- Helpers ---

def approx(a, b, tol=1e-6):
    """Assert two floats are approximately equal."""
    assert abs(a - b) < tol, f"{a} != {b} (tol={tol})"


# --- Curve Squared ---

class TestCurveSquared:

    def test_positive(self):
        approx(curve_squared(0.5), 0.25)

    def test_negative(self):
        approx(curve_squared(-0.5), -0.25)

    def test_zero(self):
        approx(curve_squared(0.0), 0.0)

    def test_one(self):
        approx(curve_squared(1.0), 1.0)

    def test_neg_one(self):
        approx(curve_squared(-1.0), -1.0)


# --- Hermite Eval ---

class TestHermiteEval:

    def test_linear_segment(self):
        """y = x over [0, 1] with slope 1 at both ends."""
        approx(hermite_eval(0.0, 1.0, 1.0, 1.0, 1.0, 0.0), 0.0)
        approx(hermite_eval(0.0, 1.0, 1.0, 1.0, 1.0, 0.5), 0.5)
        approx(hermite_eval(0.0, 1.0, 1.0, 1.0, 1.0, 1.0), 1.0)

    def test_endpoints(self):
        """Hermite always passes through endpoints."""
        approx(hermite_eval(2.0, 0.0, 5.0, 0.0, 1.0, 0.0), 2.0)
        approx(hermite_eval(2.0, 0.0, 5.0, 0.0, 1.0, 1.0), 5.0)


# --- Spline Evaluation ---

class TestSplineEvaluation:

    def test_default_spline_is_linear(self):
        """Default 3-point spline (y=x) should return x for all inputs."""
        pts = default_spline_points()
        for x in [-1.0, -0.5, 0.0, 0.5, 1.0]:
            approx(evaluate_spline(pts, x), x, tol=1e-4)

    def test_clamping(self):
        """Values outside range are clamped to endpoint values."""
        pts = default_spline_points()
        approx(evaluate_spline(pts, -2.0), -1.0)
        approx(evaluate_spline(pts, 2.0), 1.0)

    def test_few_points_passthrough(self):
        """Fewer than 2 points returns x unchanged."""
        assert evaluate_spline([], 0.5) == 0.5
        assert evaluate_spline([{"x": 0, "y": 0, "tangent": 1}], 0.5) == 0.5

    def test_yaml_4point_spline(self):
        """Test the 4-point spline from general_unit_test_mappings.yaml."""
        pts = [
            {"x": -1.0, "y": -1.0, "tangent": 10.0},
            {"x": 0.0, "y": 0.0, "tangent": 1.0},
            {"x": 0.596, "y": 0.576, "tangent": -5.125},
            {"x": 1.0, "y": 1.0, "tangent": 1.0},
        ]
        # Endpoints
        approx(evaluate_spline(pts, -1.0), -1.0, tol=1e-4)
        approx(evaluate_spline(pts, 0.0), 0.0, tol=1e-4)
        approx(evaluate_spline(pts, 0.596), 0.576, tol=1e-4)
        approx(evaluate_spline(pts, 1.0), 1.0, tol=1e-4)

    def test_numerical_slope_at_origin(self):
        """Numerical slope should match tangent at control points."""
        pts = default_spline_points()
        slope = numerical_slope(pts, 0.0)
        approx(slope, 1.0, tol=1e-2)


# --- Segment Evaluation ---

class TestSegmentEvaluation:

    def test_default_segments_linear(self):
        """Default 3-point segments (y=x) should be linear."""
        pts = default_segment_points()
        for x in [-1.0, -0.5, 0.0, 0.5, 1.0]:
            approx(evaluate_segments(pts, x), x, tol=1e-4)

    def test_clamping(self):
        """Values outside range are clamped."""
        pts = default_segment_points()
        approx(evaluate_segments(pts, -2.0), -1.0)
        approx(evaluate_segments(pts, 2.0), 1.0)

    def test_few_points_passthrough(self):
        """Fewer than 2 points returns x unchanged."""
        assert evaluate_segments([], 0.5) == 0.5
        assert evaluate_segments([{"x": 0, "y": 0}], 0.5) == 0.5

    def test_yaml_5point_segments(self):
        """Test the 5-point segments from general_unit_test_mappings.yaml."""
        pts = [
            {"x": -1.0, "y": -1.0},
            {"x": -0.672, "y": -0.396},
            {"x": 0.0, "y": 0.0},
            {"x": 0.704, "y": 0.368},
            {"x": 1.0, "y": 1.0},
        ]
        # Endpoints
        approx(evaluate_segments(pts, -1.0), -1.0)
        approx(evaluate_segments(pts, 0.0), 0.0)
        approx(evaluate_segments(pts, 1.0), 1.0)
        # Midpoint of segment [0.0, 0.0] -> [0.704, 0.368]
        # x=0.352 -> t=0.5 -> y = 0.0 + 0.5 * (0.368 - 0.0) = 0.184
        approx(evaluate_segments(pts, 0.352), 0.184, tol=1e-3)


# --- Deadband ---

class TestDeadband:

    def test_inside_deadband(self):
        assert apply_deadband(0.05, 0.1) == 0.0
        assert apply_deadband(-0.05, 0.1) == 0.0

    def test_at_boundary(self):
        approx(apply_deadband(0.1, 0.1), 0.0, tol=1e-4)

    def test_outside_deadband(self):
        # 0.55 with deadband 0.1 -> (0.55 - 0.1) / (1.0 - 0.1) = 0.5
        approx(apply_deadband(0.55, 0.1), 0.5, tol=1e-4)

    def test_negative_outside(self):
        approx(apply_deadband(-0.55, 0.1), -0.5, tol=1e-4)

    def test_zero_deadband(self):
        approx(apply_deadband(0.5, 0.0), 0.5)


# --- Shaping Pipeline ---

class TestShaperPipeline:

    def test_raw_passthrough(self):
        """RAW mode: true passthrough, no shaping applied."""
        pipeline = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.RAW, scale=1.0, extra={})
        approx(pipeline(0.5), 0.5)
        approx(pipeline(-0.5), -0.5)

    def test_raw_ignores_all_shaping(self):
        """RAW mode ignores inversion, deadband, and scale."""
        pipeline = build_shaping_pipeline(
            inversion=True, deadband=0.1,
            trigger_mode=EventTriggerMode.RAW, scale=5.5, extra={})
        # RAW returns the raw value regardless of params
        approx(pipeline(0.5), 0.5)
        approx(pipeline(-0.3), -0.3)

    def test_scaled_with_scale(self):
        pipeline = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SCALED, scale=5.5, extra={})
        approx(pipeline(1.0), 5.5)

    def test_inversion(self):
        pipeline = build_shaping_pipeline(
            inversion=True, deadband=0.0,
            trigger_mode=EventTriggerMode.SCALED, scale=1.0, extra={})
        approx(pipeline(0.5), -0.5)

    def test_scaled_mode(self):
        pipeline = build_shaping_pipeline(
            inversion=False, deadband=0.1,
            trigger_mode=EventTriggerMode.SCALED, scale=12.0, extra={})
        # 0.55 -> deadband(0.55, 0.1) = 0.5 -> * 12.0 = 6.0
        approx(pipeline(0.55), 6.0, tol=0.1)

    def test_squared_mode(self):
        pipeline = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SQUARED, scale=1.0, extra={})
        approx(pipeline(0.5), 0.25)
        approx(pipeline(-0.5), -0.25)

    def test_spline_mode(self):
        pts = default_spline_points()
        pipeline = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SPLINE, scale=1.0,
            extra={"spline_points": pts})
        # Default spline is y=x
        approx(pipeline(0.5), 0.5, tol=1e-3)

    def test_segmented_mode(self):
        pts = default_segment_points()
        pipeline = build_shaping_pipeline(
            inversion=False, deadband=0.0,
            trigger_mode=EventTriggerMode.SEGMENTED, scale=1.0,
            extra={"segment_points": pts})
        # Default segments are y=x
        approx(pipeline(0.5), 0.5, tol=1e-3)

    def test_full_pipeline_inversion_deadband_squared_scale(self):
        """Full pipeline: invert -> deadband -> squared -> scale."""
        pipeline = build_shaping_pipeline(
            inversion=True, deadband=0.05,
            trigger_mode=EventTriggerMode.SQUARED, scale=2.0, extra={})
        # Input 0.5 -> inverted = -0.5
        # -> deadband(-0.5, 0.05) ≈ -0.4737
        # -> squared ≈ -0.2244
        # -> * 2.0 ≈ -0.4488
        result = pipeline(0.5)
        assert result < 0, f"Expected negative, got {result}"
        approx(result, -0.4488, tol=0.02)
