"""
Test mode on the whole simulated robot: the Characterization chooser picks what runs.

Generated by Claude. This boots ``robot.py`` like ``robotpy sim`` does, picks
an option on the dashboard chooser through NetworkTables, enables test mode
and checks the right thing happens.
"""

import math

import ntcore
import pytest
import wpilib.simulation
from wpilib.simulation import DriverStationSim

from robot import MyRobot

_STEP_PERIOD = (MyRobot.kDefaultPeriod / 1000) - 0.001

pytestmark = pytest.mark.skipif(
    not hasattr(DriverStationSim, "setTest"), reason="RobotPy 2027 replaces test mode with op modes"
)


def step(seconds):
    for _ in range(round(seconds / 0.02)):
        DriverStationSim.notifyNewData()
        wpilib.simulation.stepTiming(_STEP_PERIOD)


def pick(option):
    """Pick an option on the dashboard's Characterization chooser, like a driver would."""
    topic = ntcore.NetworkTableInstance.getDefault().getStringTopic("/SmartDashboard/Characterization/selected")
    publisher = topic.publish()
    publisher.set(option)
    return publisher


def enable_test_mode(control):
    control.step_timing(seconds=0.5, autonomous=False, enabled=False)
    DriverStationSim.setAutonomous(False)
    DriverStationSim.setTest(True)
    DriverStationSim.setEnabled(True)
    step(0.1)


def test_module_check_runs_by_default(control, robot):
    with control.run_robot():
        enable_test_mode(control)
        step(1.0)
        assert robot.test_command is robot.characterization.selected()
        for module in robot.drivetrain.modules:
            assert abs(math.remainder(module.angle_rad, math.tau)) < math.radians(2)
        step(3.0)  # second step of the module check: 90 degrees
        for module in robot.drivetrain.modules:
            assert abs(math.remainder(module.angle_rad - math.pi / 2, math.tau)) < math.radians(2)


def test_picked_test_runs_and_stops_when_disabled(control, robot):
    publisher = pick("Wheel radius")
    with control.run_robot():
        enable_test_mode(control)
        step(3.0)
        assert robot.drivetrain.measured_speeds.omega_rad_per_s > 0.5  # spinning in place
        DriverStationSim.setEnabled(False)
        step(0.5)
        assert robot.test_command is None
        assert abs(robot.drivetrain.measured_speeds.omega_rad_per_s) < 0.1
    publisher.close()
