"""
Fuzz tester for full robot teleop.
# Generated by Claude

What is fuzz testing?
    "Fuzz testing" means feeding RANDOM inputs to the robot code to see if
    anything crashes. Think of it like a toddler mashing every button on the
    Xbox controller at the same time, hundreds of times in a row. If the
    robot code survives without crashing, we know it's pretty robust.

Why do we have this?
    When you deploy code (make deploy) or open a pull request, tests run
    automatically. These fuzz tests make sure that NO combination of
    controller inputs can crash the robot during a match. This catches
    bugs that are hard to find by hand, like:
      - A button combo that triggers an unhandled exception
      - Stick values that cause a division-by-zero in drive math
      - Commands that conflict when two buttons are pressed together
      - Code that accidentally depends on auto running before teleop

How does it work?
    1. The test boots the full robot in simulation (same code that runs
       on the real robot).
    2. It walks through a realistic match: disabled -> autonomous -> teleop.
    3. During teleop, it generates random controller inputs each cycle
       (every 20ms, just like a real match) and feeds them to the robot.
    4. If the robot crashes at any point, the test fails and tells you
       exactly which seed and cycle caused it.

What is a "seed"?
    Each test uses a specific random seed number (like seed=42). This means
    the "random" inputs are actually the SAME every time you run the test.
    If a test fails, anyone on the team can re-run it and get the exact
    same failure. This makes bugs easy to reproduce and fix.

What do I do if a fuzz test fails?
    1. Read the error message - it will show the exception and the seed.
    2. Run just that one test to see the full traceback:
         python -m robotpy test -- tests/test_fuzz_teleop.py::test_fuzz_teleop_default -v
    3. The traceback will point to the line in your code that crashed.
    4. Fix the bug in your subsystem/command code (NOT in this test file).
    5. Re-run the tests to confirm the fix.

    Common fixes:
    - Add a None check before using a value
    - Handle edge cases in your math (like division by zero)
    - Make sure commands don't conflict with each other

How to run these tests:
    # Run just the fuzz tests
    python -m robotpy test -- tests/test_fuzz_teleop.py -v

    # Run a single fuzz test
    python -m robotpy test -- tests/test_fuzz_teleop.py::test_fuzz_teleop_short -v

    # Run ALL tests (fuzz + everything else)
    python -m robotpy test

How it detects crashes:
    - robot.py's __callAndCatch method re-raises exceptions in sim mode,
      so any crash in teleopPeriodic/robotPeriodic becomes a test failure.
    - pyfrc's reraise fixture catches exceptions from the robot thread.
    - pyfrc.isolated = true (in pyproject.toml) runs each test in its own
      process so tests can't interfere with each other.
"""

import random
from dataclasses import dataclass, field

import pytest
import wpilib.simulation
from wpilib.simulation import XboxControllerSim, DriverStationSim

from robot import MyRobot

# Step slightly under the robot's periodic period to avoid triggering
# loop overrun detection (which fires at exactly the period boundary).
_STEP_PERIOD = (MyRobot.kDefaultPeriod / 1000) - 0.001


# ---------------------------------------------------------------------------
# Controller input snapshot
# ---------------------------------------------------------------------------

@dataclass
class ControllerInputs:
    """Snapshot of all 17 Xbox controller inputs.

    This represents the state of one Xbox controller at a single moment
    in time. Sticks and triggers are floats, buttons are booleans, and
    the POV (D-pad) is an angle in degrees or -1 when not pressed.
    """
    # Analog axes (range -1.0 to 1.0, triggers 0.0 to 1.0)
    left_x: float = 0.0
    left_y: float = 0.0
    right_x: float = 0.0
    right_y: float = 0.0
    left_trigger: float = 0.0
    right_trigger: float = 0.0

    # Digital buttons
    a: bool = False
    b: bool = False
    x: bool = False
    y: bool = False
    left_bumper: bool = False
    right_bumper: bool = False
    back: bool = False
    start: bool = False
    left_stick: bool = False
    right_stick: bool = False

    # POV / D-pad (-1 = released, 0/45/90/.../315 = pressed direction)
    pov: int = -1


def apply_inputs(sim: XboxControllerSim, inputs: ControllerInputs):
    """Push a ControllerInputs snapshot into the simulated Xbox controller.

    This is like physically moving the sticks and pressing buttons on a
    real controller, but done in code. The sim object talks to the same
    WPILib layer that the real XboxController reads from.
    """
    sim.setLeftX(inputs.left_x)
    sim.setLeftY(inputs.left_y)
    sim.setRightX(inputs.right_x)
    sim.setRightY(inputs.right_y)
    sim.setLeftTriggerAxis(inputs.left_trigger)
    sim.setRightTriggerAxis(inputs.right_trigger)

    sim.setAButton(inputs.a)
    sim.setBButton(inputs.b)
    sim.setXButton(inputs.x)
    sim.setYButton(inputs.y)
    sim.setLeftBumperButton(inputs.left_bumper)
    sim.setRightBumperButton(inputs.right_bumper)
    sim.setBackButton(inputs.back)
    sim.setStartButton(inputs.start)
    sim.setLeftStickButton(inputs.left_stick)
    sim.setRightStickButton(inputs.right_stick)

    sim.setPOV(0, inputs.pov)
    sim.notifyNewData()


# ---------------------------------------------------------------------------
# Fuzz input generator
# ---------------------------------------------------------------------------

_POV_VALUES = [-1, 0, 45, 90, 135, 180, 225, 270, 315]

_BUTTON_FIELDS = [
    "a", "b", "x", "y",
    "left_bumper", "right_bumper",
    "back", "start",
    "left_stick", "right_stick",
]

_AXIS_FIELDS = [
    "left_x", "left_y", "right_x", "right_y",
    "left_trigger", "right_trigger",
]

_TRIGGER_AXES = {"left_trigger", "right_trigger"}


@dataclass
class FuzzInputGenerator:
    """Generates random-but-reproducible controller inputs each cycle.

    How it works:
    - Uses a seeded Random so the same seed always produces the same
      sequence of inputs. This makes failures reproducible.
    - Each cycle, every button has a 30% chance of toggling (pressed
      becomes released, or vice versa). This creates realistic "hold"
      patterns instead of flickering every cycle.
    - Each cycle, every axis has a 50% chance of changing. When it
      changes, it picks one of three modes:
        * "jump"    - teleport to a random value (like flicking a stick)
        * "ramp"    - small nudge from current value (like slowly moving)
        * "extreme" - snap to -1, 0, or +1 (like slamming a stick)
    - The extreme_bias parameter (0.0 to 1.0) controls how often
      "extreme" mode is forced. Set to 1.0 to ONLY test boundary values.
    """
    seed: int
    num_controllers: int = 2
    button_change_prob: float = 0.30
    axis_change_prob: float = 0.50
    extreme_bias: float = 0.0  # 0.0 = normal mix, 1.0 = always extremes

    rng: random.Random = field(init=False)
    states: list = field(init=False)

    def __post_init__(self):
        self.rng = random.Random(self.seed)
        self.states = [ControllerInputs() for _ in range(self.num_controllers)]

    def next_cycle(self) -> list[ControllerInputs]:
        """Generate the next set of controller inputs for all controllers."""
        for state in self.states:
            self._mutate(state)
        return self.states

    def _mutate(self, state: ControllerInputs):
        rng = self.rng

        # Buttons: toggle with probability
        for btn in _BUTTON_FIELDS:
            if rng.random() < self.button_change_prob:
                setattr(state, btn, not getattr(state, btn))

        # Axes: change with probability using one of three modes
        for axis in _AXIS_FIELDS:
            if rng.random() < self.axis_change_prob:
                current = getattr(state, axis)
                is_trigger = axis in _TRIGGER_AXES

                # Select mode: extreme slam vs (random jump or smooth ramp)
                if rng.random() < self.extreme_bias:
                    mode = "extreme"
                else:
                    mode = rng.choice(["jump", "ramp", "extreme"])

                if mode == "extreme":
                    if is_trigger:
                        value = rng.choice([0.0, 1.0])
                    else:
                        value = rng.choice([-1.0, 0.0, 1.0])
                elif mode == "jump":
                    if is_trigger:
                        value = rng.uniform(0.0, 1.0)
                    else:
                        value = rng.uniform(-1.0, 1.0)
                else:  # ramp
                    delta = rng.uniform(-0.2, 0.2)
                    value = current + delta
                    if is_trigger:
                        value = max(0.0, min(1.0, value))
                    else:
                        value = max(-1.0, min(1.0, value))

                setattr(state, axis, value)

        # POV: small chance of changing
        if rng.random() < self.button_change_prob:
            state.pov = rng.choice(_POV_VALUES)


# ---------------------------------------------------------------------------
# Shared test runner
# ---------------------------------------------------------------------------

def _run_fuzz(
    control,
    *,
    cycles: int,
    seed: int,
    skip_auto: bool = False,
    extreme_bias: float = 0.0,
    num_controllers: int = 2,
):
    """Run a fuzz test through the full match lifecycle.

    Simulates a complete FRC match in order:
      1. Disabled (0.5s)  - robot boots up, subsystems initialize
      2. Autonomous (1.0s) - auto routine runs (skipped if skip_auto=True)
      3. Teleop (N cycles) - random controller inputs every 20ms
      4. Disabled (0.5s)  - robot shuts down cleanly

    Each teleop cycle is one 20ms tick (same as a real match). The test
    checks that the robot is still alive after every single cycle.

    Args:
        control: pyfrc TestController fixture (provided automatically by
            pyfrc - you don't need to create this yourself).
        cycles: How many 20ms teleop cycles to run. 500 cycles = 10
            seconds of simulated match time.
        seed: RNG seed for reproducibility. Same seed = same inputs.
        skip_auto: If True, jump straight from disabled to teleop.
            This catches bugs where code assumes autonomousInit() ran
            before teleopInit().
        extreme_bias: 0.0 = normal mix of input modes, 1.0 = always
            snap axes to -1/0/+1 boundary values.
        num_controllers: Number of Xbox controllers to simulate.
            Default is 2 (driver + mech operator).
    """
    gen = FuzzInputGenerator(
        seed=seed,
        num_controllers=num_controllers,
        extreme_bias=extreme_bias,
    )

    # Create sim controllers for each port
    sims = [XboxControllerSim(port) for port in range(num_controllers)]

    with control.run_robot():
        # Phase 1: Disabled warm-up
        control.step_timing(seconds=0.5, autonomous=False, enabled=False)

        # Phase 2: Autonomous (optional)
        if not skip_auto:
            control.step_timing(seconds=1.0, autonomous=True, enabled=True)

        # Transition to teleop — we use raw stepTiming here (and in the fuzz
        # loop below) instead of control.step_timing because we need per-tick
        # control to inject different random inputs each cycle. control.step_timing
        # steps multiple ticks at once with no per-tick callback.
        DriverStationSim.setAutonomous(False)
        DriverStationSim.setEnabled(True)
        DriverStationSim.notifyNewData()
        wpilib.simulation.stepTiming(_STEP_PERIOD)

        # Phase 3: Teleop fuzz
        for cycle in range(cycles):
            inputs_list = gen.next_cycle()
            for sim, inputs in zip(sims, inputs_list):
                apply_inputs(sim, inputs)

            DriverStationSim.notifyNewData()
            wpilib.simulation.stepTiming(_STEP_PERIOD)

            assert control.robot_is_alive, (
                f"Robot died during teleop fuzz cycle {cycle} (seed={seed})"
            )

        # Phase 4: Disabled cool-down
        control.step_timing(seconds=0.5, autonomous=False, enabled=False)


# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

def test_fuzz_teleop_default(control):
    """Standard fuzz with the full match flow: disabled -> auto -> teleop.

    This is the main fuzz test. It runs 500 cycles (10 seconds of match
    time) with seed 42. If this test fails, it means some combination of
    controller inputs crashed the robot during a normal match sequence.
    """
    _run_fuzz(control, cycles=500, seed=42)


def test_fuzz_teleop_skip_auto(control):
    """Same random inputs as default, but skips the autonomous period.

    Why? Some code might assume that autonomousInit() always runs before
    teleopInit(). In a real match this is true, but during testing or
    practice mode it might not be. This test catches those assumptions.
    """
    _run_fuzz(control, cycles=500, seed=42, skip_auto=True)


def test_fuzz_teleop_short(control):
    """Quick 100-cycle smoke test with a different seed.

    Use this as a fast sanity check while developing. It runs in about
    2 seconds of simulated time.
    """
    _run_fuzz(control, cycles=100, seed=7)


def test_fuzz_teleop_all_extremes(control):
    """Every stick/trigger value snaps to boundary values (-1, 0, or +1).

    This specifically targets edge cases in drive math and deadband logic
    by only using extreme inputs. If your code divides by a stick value
    or doesn't handle full-speed correctly, this test will find it.
    """
    _run_fuzz(control, cycles=200, seed=99, extreme_bias=1.0)


@pytest.mark.slow
def test_fuzz_teleop_long(control):
    """Thorough fuzz test: 5000 cycles (100 seconds of simulated match).

    This runs a LOT of random inputs to catch rare edge cases. It's
    marked @pytest.mark.slow so you can skip it during quick local
    testing if needed. It still runs in CI on every pull request.
    """
    _run_fuzz(control, cycles=5000, seed=314)
