"""Unit tests for VirtualAnalogGenerator.
# Generated by Claude

Tests the physics model that converts button presses into ramped
analog values.  Uses pure-Python mode (no wpilib) with explicit
default_dt for deterministic results.
"""

import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# Prevent wpilib import in generator so it uses default_dt
import unittest.mock
_mock_wpilib = unittest.mock.MagicMock()
sys.modules.setdefault('wpilib', _mock_wpilib)

# Force the virtual_analog module to see _get_time as None
# by patching after import
from utils.input import virtual_analog as va_mod
va_mod._get_time = None

from utils.controller.model import (
    ActionDefinition,
    InputType,
    EventTriggerMode,
    EXTRA_VA_RAMP_RATE,
    EXTRA_VA_ACCELERATION,
    EXTRA_VA_NEGATIVE_RAMP_RATE,
    EXTRA_VA_NEGATIVE_ACCELERATION,
    EXTRA_VA_ZERO_VEL_ON_RELEASE,
    EXTRA_VA_TARGET_VALUE,
    EXTRA_VA_REST_VALUE,
)
from utils.input.virtual_analog import VirtualAnalogGenerator


DT = 0.02  # 20ms step


def _make_action(**extra_overrides) -> ActionDefinition:
    """Create a VIRTUAL_ANALOG action with given extra params."""
    extra = {}
    extra.update(extra_overrides)
    return ActionDefinition(
        name="test_va",
        group="test",
        input_type=InputType.VIRTUAL_ANALOG,
        trigger_mode=EventTriggerMode.SCALED,
        extra=extra,
    )


def _step(gen, n=1):
    """Advance the generator n steps."""
    for _ in range(n):
        gen.update()
    return gen.get_value()


class TestInstantJump:
    """ramp_rate=0 means instant jump to target/rest."""

    def test_instant_jump_to_target(self):
        pressed = [False]
        action = _make_action(**{EXTRA_VA_RAMP_RATE: 0.0})
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        assert gen.get_value() == 0.0

        pressed[0] = True
        _step(gen)
        assert gen.get_value() == 1.0

    def test_instant_jump_to_rest(self):
        pressed = [True]
        action = _make_action(**{EXTRA_VA_RAMP_RATE: 0.0})
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        _step(gen)
        assert gen.get_value() == 1.0

        pressed[0] = False
        _step(gen)
        assert gen.get_value() == 0.0


class TestTriangleWave:
    """acceleration=0, ramp_rate>0: constant velocity ramp."""

    def test_linear_ramp_up(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 5.0,
            EXTRA_VA_ACCELERATION: 0.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # After 1 step: position = 5.0 * 0.02 = 0.1
        _step(gen)
        assert abs(gen.get_value() - 0.1) < 1e-6

        # After 10 steps total: position = 5.0 * 0.2 = 1.0
        _step(gen, 9)
        assert abs(gen.get_value() - 1.0) < 1e-6

    def test_linear_ramp_down(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 50.0,
            EXTRA_VA_ACCELERATION: 0.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Ramp to 1.0 instantly (50 units/s * 0.02 = 1.0 per step)
        _step(gen)
        assert gen.get_value() == 1.0

        pressed[0] = False
        # Should ramp down at 50 units/s
        _step(gen)
        assert abs(gen.get_value()) < 1e-6

    def test_clamped_at_target(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 100.0,
            EXTRA_VA_ACCELERATION: 0.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Should not exceed target (1.0)
        _step(gen, 10)
        assert gen.get_value() == 1.0


class TestAcceleration:
    """acceleration>0: velocity increases over time."""

    def test_velocity_ramps_up(self):
        """Acceleration-only mode (ramp_rate=0): v = u + a*t, no cap."""
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 0.0,
            EXTRA_VA_ACCELERATION: 5.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Step 1: velocity = 5.0 * 0.02 = 0.1, position = 0.1 * 0.02 = 0.002
        _step(gen)
        val1 = gen.get_value()
        assert val1 > 0

        # Step 2: velocity = 0.2, position += 0.2 * 0.02 = 0.004
        _step(gen)
        val2 = gen.get_value()
        assert val2 > val1

        # Position should increase with accelerating rate
        delta1 = val1
        delta2 = val2 - val1
        assert delta2 > delta1

    def test_ramp_rate_wins_over_acceleration(self):
        """When both ramp_rate and acceleration are set, ramp_rate wins
        (constant velocity) and acceleration is ignored."""
        # Generated by Claude
        import warnings
        pressed = [True]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            action = _make_action(**{
                EXTRA_VA_RAMP_RATE: 1.0,
                EXTRA_VA_ACCELERATION: 1000.0,
            })
            gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # ramp_rate wins: constant velocity of 1.0, position = 1.0 * 0.02
        _step(gen)
        assert abs(gen.get_value() - 0.02) < 1e-6
        # Second step same delta (constant velocity, not accelerating)
        _step(gen)
        assert abs(gen.get_value() - 0.04) < 1e-6


class TestRelease:
    """Release behavior tests."""

    def test_zero_velocity_on_release(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 5.0,
            EXTRA_VA_ACCELERATION: 0.0,
            EXTRA_VA_ZERO_VEL_ON_RELEASE: True,
            EXTRA_VA_NEGATIVE_RAMP_RATE: 2.0,
            EXTRA_VA_NEGATIVE_ACCELERATION: 0.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Ramp up for 5 steps: position = 5 * 5 * 0.02 = 0.5
        _step(gen, 5)
        pos_at_release = gen.get_value()
        assert abs(pos_at_release - 0.5) < 1e-6

        # Release: velocity zeroed, then ramps down at 2.0 units/s
        pressed[0] = False
        _step(gen)
        # After 1 step of release: position = 0.5 - 2.0 * 0.02 = 0.46
        assert abs(gen.get_value() - 0.46) < 1e-6

    def test_asymmetric_negative_ramp_rate(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 50.0,
            EXTRA_VA_ACCELERATION: 0.0,
            EXTRA_VA_NEGATIVE_RAMP_RATE: 2.0,
            EXTRA_VA_NEGATIVE_ACCELERATION: 0.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Instant to 1.0
        _step(gen)
        assert gen.get_value() == 1.0

        pressed[0] = False
        _step(gen)
        # Ramps down slowly: 1.0 - 2.0 * 0.02 = 0.96
        assert abs(gen.get_value() - 0.96) < 1e-6

    def test_asymmetric_negative_acceleration(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 50.0,
            EXTRA_VA_ACCELERATION: 0.0,
            EXTRA_VA_NEGATIVE_RAMP_RATE: 10.0,
            EXTRA_VA_NEGATIVE_ACCELERATION: 5.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        _step(gen)
        assert gen.get_value() == 1.0

        pressed[0] = False
        # Release: velocity from pressing (+50) gets capped to negative
        # ramp_rate (10.0) in the -1 direction → velocity = -10.0
        # position = 1.0 + (-10.0) * 0.02 = 0.8
        _step(gen)
        assert gen.get_value() < 1.0
        assert abs(gen.get_value() - 0.8) < 1e-6


class TestClamping:
    """Output clamping tests."""

    def test_clamped_to_rest_target_range(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 100.0,
            EXTRA_VA_ACCELERATION: 0.0,
            EXTRA_VA_TARGET_VALUE: 0.5,
            EXTRA_VA_REST_VALUE: -0.3,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        _step(gen, 100)
        assert gen.get_value() == 0.5

        pressed[0] = False
        _step(gen, 100)
        assert gen.get_value() == -0.3


class TestConfigurableRestTarget:
    """Custom rest_value and target_value."""

    def test_custom_rest_and_target(self):
        pressed = [False]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 0.0,
            EXTRA_VA_TARGET_VALUE: 0.8,
            EXTRA_VA_REST_VALUE: -0.5,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Starts at rest_value
        assert gen.get_value() == -0.5

        pressed[0] = True
        _step(gen)
        assert gen.get_value() == 0.8

        pressed[0] = False
        _step(gen)
        assert gen.get_value() == -0.5

    def test_negative_to_positive_range(self):
        pressed = [True]
        action = _make_action(**{
            EXTRA_VA_RAMP_RATE: 10.0,
            EXTRA_VA_ACCELERATION: 0.0,
            EXTRA_VA_TARGET_VALUE: 1.0,
            EXTRA_VA_REST_VALUE: -1.0,
        })
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        # Starts at rest = -1.0, ramps toward 1.0 at 10 units/s
        assert gen.get_value() == -1.0
        _step(gen)
        # position = -1.0 + 10 * 0.02 = -0.8
        assert abs(gen.get_value() - (-0.8)) < 1e-6


class TestReset:
    """Generator reset behavior."""

    def test_reset_returns_to_rest(self):
        pressed = [True]
        action = _make_action(**{EXTRA_VA_RAMP_RATE: 0.0})
        gen = VirtualAnalogGenerator(action, lambda: pressed[0], DT)

        _step(gen)
        assert gen.get_value() == 1.0

        gen.reset()
        assert gen.get_value() == 0.0
