"""
Tests for the per-mechanism SysId builders in utils/sysid/mech/.

Generated by Claude. Each builder should set the right units, gravity and
limits, refuse to build a mechanism that is missing something it needs,
and the drivetrain's travel limit should stop a test that runs out of room.
"""

import doctest
import importlib
import math

import commands2
import pytest
from wpilib.simulation import DriverStationSim, pauseTiming, resumeTiming

from sysid_fakes import FakeMotor, run_until_done
from utils.sysid.characterizable import Gravity, Reading
from utils.sysid.mech.arm import ARM_SYSID, arm
from utils.sysid.mech.drivetrain import drivetrain
from utils.sysid.mech.elevator import elevator
from utils.sysid.mech.flywheel import flywheel
from utils.sysid.mech.rotary import rotary
from utils.sysid.routines import SysIdTests
from utils.sysid.settings import SysIdSettings


@pytest.fixture
def scheduler():
    """A command scheduler with the robot enabled, and simulated time we step by hand."""
    pauseTiming()
    DriverStationSim.setEnabled(True)
    DriverStationSim.notifyNewData()
    commands2.CommandScheduler.resetInstance()
    yield commands2.CommandScheduler.getInstance()
    commands2.CommandScheduler.getInstance().cancelAll()
    commands2.CommandScheduler.resetInstance()
    DriverStationSim.resetData()
    DriverStationSim.notifyNewData()
    resumeTiming()


def parts():
    return {"subsystem": commands2.Subsystem(), "set_voltage": lambda volts: None, "read": lambda: Reading(0, 0, 0)}


class TestBuilders:
    def test_flywheel_turns_with_no_limits(self):
        wheel = flywheel("shooter", **parts())
        assert wheel.angular and wheel.gravity == Gravity.NONE
        assert wheel.min_position is None and wheel.max_position is None and wheel.max_travel is None

    def test_drivetrain_is_linear_with_a_travel_limit(self):
        drive = drivetrain("drive", max_travel_m=4.0, **parts())
        assert not drive.angular
        assert drive.max_travel == 4.0
        assert drive.settings.step_volts < 7.0  # smaller than WPILib's, to stop wheel slip

    def test_drivetrain_needs_room(self):
        with pytest.raises(ValueError):
            drivetrain("drive", max_travel_m=0.0, **parts())

    def test_rotary_limits_are_optional(self):
        assert rotary("steer", **parts()).max_position is None
        assert rotary("turret", min_rad=-3.0, max_rad=3.0, **parts()).min_position == -3.0

    def test_arm_has_gravity_and_gentle_defaults(self):
        pivot = arm("pivot", min_rad=-1.0, max_rad=1.0, **parts())
        assert pivot.gravity == Gravity.ARM and pivot.angular
        assert pivot.settings == ARM_SYSID
        assert pivot.settings.max_volts <= 6.0

    def test_elevator_has_gravity(self):
        lift = elevator("lift", min_m=0.0, max_m=1.0, **parts())
        assert lift.gravity == Gravity.ELEVATOR and not lift.angular

    @pytest.mark.parametrize("build", [arm, rotary])
    def test_backwards_limits_are_refused(self, build):
        with pytest.raises(ValueError, match="below"):
            build("x", min_rad=1.0, max_rad=-1.0, **parts())

    def test_degrees_are_caught(self):
        with pytest.raises(ValueError, match="degrees"):
            arm("pivot", min_rad=-80.0, max_rad=80.0, **parts())

    def test_elevator_limits_are_not_checked_for_degrees(self):
        assert elevator("lift", min_m=0.0, max_m=8.0, **parts()).max_position == 8.0

    def test_arm_needs_limits(self):
        with pytest.raises(TypeError):
            arm("pivot", **parts())  # type: ignore[call-arg]


class TestTravelLimit:
    def test_stops_after_moving_its_travel(self, scheduler):
        fake = FakeMotor()
        fake.motor.position = 10.0  # the limit counts from where the test starts, not from 0
        mechanism = drivetrain(
            "fake",
            subsystem=fake,
            set_voltage=fake.set_voltage,
            read=fake.read,
            max_travel_m=1.0,
            settings=SysIdSettings(ramp_volts_per_s=2.0, timeout_s=20.0),
        )
        tests = SysIdTests(mechanism)
        seconds = run_until_done(scheduler, tests.quasistatic(forward=True))
        assert seconds < 15.0  # well before the 20 s timeout
        assert 1.0 <= tests.runs[-1][-1].position - 10.0 < 1.1
        assert fake.volts == 0.0

    def test_reverse_travel_counts_too(self, scheduler):
        fake = FakeMotor()
        mechanism = drivetrain("fake", subsystem=fake, set_voltage=fake.set_voltage, read=fake.read, max_travel_m=1.0)
        tests = SysIdTests(mechanism)
        run_until_done(scheduler, tests.dynamic(forward=False))
        assert -1.1 < tests.runs[-1][-1].position <= -1.0


@pytest.mark.parametrize(
    "module_name",
    [
        "utils.sysid.mech.flywheel",
        "utils.sysid.mech.drivetrain",
        "utils.sysid.mech.rotary",
        "utils.sysid.mech.arm",
        "utils.sysid.mech.elevator",
    ],
)
def test_docstring_examples(module_name):
    result = doctest.testmod(importlib.import_module(module_name), optionflags=doctest.ELLIPSIS)
    assert result.attempted > 0
    assert result.failed == 0


def test_a_full_turn_in_radians_is_allowed():
    assert rotary("x", min_rad=-math.tau, max_rad=math.tau, **parts()).max_position == math.tau
