"""Visual deadband test — sweeps a joystick axis and graphs input vs output.
# Generated by Claude

Skipped by default (addopts = -m 'not graph'). Run explicitly with:
    pytest tests/test_deadband_graph.py -m graph -s

Or directly:
    python tests/test_deadband_graph.py

Requires matplotlib (not in CI): pip install matplotlib
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest  # noqa: E402

from utils.input.shaping import build_shaping_pipeline  # noqa: E402
from utils.controller.model import (  # noqa: E402
    ActionDefinition,
    ControllerConfig,
    EventTriggerMode,
    FullConfig,
    InputType,
)


def _setup_plot():
    """Import matplotlib with non-interactive backend. Returns (plt, module)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


def _init_hal():
    """Initialize HAL for sim joystick access. Idempotent."""
    import hal
    try:
        hal.initialize(500, 0)
    except Exception:
        pass  # Already initialized


@pytest.mark.graph
def test_deadband_sweep():
    """Sweep input from -1 to 1 in 0.05 steps, graph input vs shaped output."""
    plt = _setup_plot()
    deadband = 0.1
    scale = 1.0

    pipeline = build_shaping_pipeline(
        inversion=False,
        deadband=deadband,
        trigger_mode=EventTriggerMode.SCALED,
        scale=scale,
        extra={},
    )

    # Sweep from -1 to 1 in 0.05 steps
    steps = []
    raw_val = -1.0
    while raw_val <= 1.0 + 1e-9:
        steps.append(round(raw_val, 4))
        raw_val += 0.05

    outputs = [pipeline(v) for v in steps]

    # Print table
    print(f"\n{'Input':>8}  {'Output':>8}")
    print("-" * 20)
    for inp, out in zip(steps, outputs):
        print(f"{inp:8.4f}  {out:8.4f}")

    # Verify deadband behavior
    for inp, out in zip(steps, outputs):
        if abs(inp) < deadband:
            assert out == 0.0, f"Expected 0 inside deadband, got {out} for input {inp}"

    # Verify continuity at deadband boundary (no jump)
    for inp, out in zip(steps, outputs):
        if abs(abs(inp) - deadband) < 0.01:
            assert abs(out) < 0.02, (
                f"Expected near-zero at deadband edge, got {out} for input {inp}"
            )

    # Verify endpoints
    assert outputs[0] == pytest.approx(-1.0, abs=0.01)
    assert outputs[-1] == pytest.approx(1.0, abs=0.01)

    # Graph
    out_path = os.path.join(os.path.dirname(__file__), "deadband_sweep.png")
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.plot(steps, steps, "--", color="gray", alpha=0.5, label="No deadband (y=x)")
    ax.plot(steps, outputs, "-o", markersize=3, label=f"Deadband={deadband}")
    ax.axvspan(-deadband, deadband, alpha=0.15, color="red", label="Deadband zone")
    ax.set_xlabel("Raw joystick input")
    ax.set_ylabel("Shaped output")
    ax.set_title(f"Deadband Sweep (deadband={deadband}, scale={scale})")
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xlim(-1.1, 1.1)
    ax.set_ylim(-1.1, 1.1)
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"\nGraph saved to: {out_path}")


@pytest.mark.graph
def test_deadband_sweep_sim_joystick():
    """Full integration: 4 deadband values on 4 axes via sim joystick.

    Each axis gets a different deadband (0, 0.05, 0.1, 0.5) and is
    plotted in a different color on the same graph.
    Axes: left_stick_x (0), left_stick_y (1), right_stick_x (2), right_stick_y (3)
    Y axes are inverted (wpilib convention: pushing forward = negative).
    """
    plt = _setup_plot()
    _init_hal()
    import wpilib.simulation  # noqa: E402
    from utils.input import InputFactory

    scale = 1.0

    # Config: 4 actions with different deadbands, each on a different axis
    # Y axes need inversion=True (stick forward = negative in wpilib)
    # Sim raw axis indices: LX=0, LY=1, LT=2, RT=3, RX=4, RY=5
    test_cases = [
        # (action_name, input_name, sim_axis_index, deadband, invert, color)
        ("test.lx_db0",   "left_stick_x",  0, 0.0,  False, "blue"),
        ("test.ly_db005", "left_stick_y",  1, 0.05, True,  "green"),
        ("test.rx_db01",  "right_stick_x", 4, 0.1,  False, "orange"),
        ("test.ry_db05",  "right_stick_y", 5, 0.5,  True,  "red"),
    ]

    # Set up simulated joystick on port 0
    js = wpilib.simulation.JoystickSim(0)
    js.setAxisCount(6)
    js.setButtonCount(10)
    js.notifyNewData()

    # Build config with all 4 actions
    actions = {}
    bindings = {}
    for action_name, input_name, _, deadband, invert, _ in test_cases:
        group, name = action_name.split(".")
        actions[action_name] = ActionDefinition(
            name=name,
            group=group,
            input_type=InputType.ANALOG,
            trigger_mode=EventTriggerMode.SCALED,
            deadband=deadband,
            inversion=invert,
            scale=scale,
        )
        bindings[input_name] = [action_name]

    config = FullConfig(
        actions=actions,
        controllers={
            0: ControllerConfig(
                port=0, name="Driver", bindings=bindings,
            )
        },
    )

    factory = InputFactory(config=config, register_global=False)

    # Build sweep steps
    steps = []
    raw_val = -1.0
    while raw_val <= 1.0 + 1e-9:
        steps.append(round(raw_val, 4))
        raw_val += 0.05

    # Sweep each axis and collect outputs
    all_outputs = {}
    for action_name, _, axis_idx, deadband, invert, color in test_cases:
        analog = factory.getAnalog(action_name)
        outputs = []
        for v in steps:
            # For inverted Y axes, send the negated value so the
            # "forward" direction in our sweep matches positive output
            sim_val = -v if invert else v
            js.setRawAxis(axis_idx, sim_val)
            js.notifyNewData()
            outputs.append(analog.get())
        all_outputs[action_name] = outputs

    # Print table
    header = f"{'Input':>8}"
    for name, _, _, db, _, _ in test_cases:
        header += f"  {'db=' + str(db):>10}"
    print(f"\n{header}")
    print("-" * len(header))
    for i, inp in enumerate(steps):
        row = f"{inp:8.4f}"
        for name, _, _, _, _, _ in test_cases:
            row += f"  {all_outputs[name][i]:10.4f}"
        print(row)

    # Verify deadband behavior for each action
    for action_name, _, _, deadband, _, _ in test_cases:
        outputs = all_outputs[action_name]
        for inp, out in zip(steps, outputs):
            if deadband > 0 and abs(inp) < deadband:
                assert abs(out) < 1e-6, (
                    f"{action_name}: expected 0 inside deadband "
                    f"(db={deadband}), got {out} for input {inp}"
                )
        # Endpoints should reach +/-1 (deadband rescales to full range)
        assert outputs[0] == pytest.approx(-1.0, abs=0.01), (
            f"{action_name}: endpoint -1 failed: {outputs[0]}")
        assert outputs[-1] == pytest.approx(1.0, abs=0.01), (
            f"{action_name}: endpoint +1 failed: {outputs[-1]}")

    # Graph — all 4 curves on one plot
    out_path = os.path.join(os.path.dirname(__file__), "deadband_sweep_sim.png")
    fig, ax = plt.subplots(figsize=(10, 7))
    ax.plot(steps, steps, "--", color="gray", alpha=0.4, label="No deadband (y=x)")

    for action_name, _, _, deadband, _, color in test_cases:
        ax.plot(steps, all_outputs[action_name], "-o", markersize=2,
                color=color, label=f"Deadband={deadband}")

    # Shade the largest deadband zone for visual reference
    ax.axvspan(-0.5, 0.5, alpha=0.06, color="red")
    ax.axvspan(-0.1, 0.1, alpha=0.08, color="orange")
    ax.axvspan(-0.05, 0.05, alpha=0.10, color="green")

    ax.set_xlabel("Raw joystick input (sim)")
    ax.set_ylabel("Shaped output (via InputFactory)")
    ax.set_title(
        "Sim Joystick Deadband Comparison\n"
        "(4 axes, deadbands: 0, 0.05, 0.1, 0.5)"
    )
    ax.legend(loc="upper left")
    ax.grid(True, alpha=0.3)
    ax.set_xlim(-1.1, 1.1)
    ax.set_ylim(-1.1, 1.1)
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"\nGraph saved to: {out_path}")


if __name__ == "__main__":
    pytest.main([__file__, "-m", "graph", "-v", "-s"])
